# Microsoft Movie Studios

Author: Mario Mocombe

**Overview**

A one-paragraph overview of the project, including the business problem, data, methods, results and recommendations.

## Business Problem

Microsoft sees all the big companies creating original video content and they want to get in on the fun. They have decided to create a new movie studio, but they don’t know anything about creating movies. You are charged with exploring what types of films are currently doing the best at the box office. You must then translate those findings into actionable insights that the head of Microsoft's new movie studio can use to help decide what type of films to create.

Questions to consider:

* What are the business's plan points related to this project?
* How did you pick the data analysis question(s) that you did?
* Why are these questions important from a business perspective?

## Data Understanding

Note that this data may not reflect the most up-to-date box office information.


1) im.db.zip 

    A zipped SQLite database containing movie data from the website Internet Movie Data Base.  The most relevant tables are         movie_basics and movie_ratings.

2) bom.movie_gross.csv.gz

    A compressed CSV file containing box office data from the website Box Office Mojo.

Questions to consider:

* Where did the data come from, and how do they relate to the data analysis questions?
* What do the data represent? Who is in the sample and what variables are included?
* What is the target variable?
* What are the properties of the variables you intend to use?

In [1]:
##Import Standard Packages
import pandas as pd
import numpy as np
import sqlite3
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

# 1 IMDB DATABASE

In [2]:
### making a connection with the IMDB DATABASE using SQLite3
conn = sqlite3.connect('zippedData/im.db')

In [3]:
### setting up a cursor so I'm able to move through the database.
### Let's continue on and create a cursor.
##A cursor object is what can actually execute SQL commands. You create it by calling .cursor() on the connection.

cur = conn.cursor()
# (This is a special query for finding the table names. 
cur.execute("""SELECT name FROM sqlite_master WHERE type = 'table';""")

In [4]:
## Use the fetchall method to find out the table names
## Fetch the result and store it in table_names
table_names = cur.fetchall()
table_names

[('movie_basics',),
 ('directors',),
 ('known_for',),
 ('movie_akas',),
 ('movie_ratings',),
 ('persons',),
 ('principals',),
 ('writers',)]

In [5]:
pd.read_sql("SELECT * FROM movie_basics;", conn)

,movie_id,primary_title,original_title,start_year,runtime_minutes,genres
0,tt0063540,Sunghursh,Sunghursh,2013,175.0,"Action,Crime,Drama"
1,tt0066787,One Day Before the Rainy Season,Ashad Ka Ek Din,2019,114.0,"Biography,Drama"
2,tt0069049,The Other Side of the Wind,The Other Side of the Wind,2018,122.0,Drama
3,tt0069204,Sabse Bada Sukh,Sabse Bada Sukh,2018,NaN,"Comedy,Drama"
4,tt0100275,The Wandering Soap Opera,La Telenovela Errante,2017,80.0,"Comedy,Drama,Fantasy"
...,...,...,...,...,...,...
146139,tt9916538,Kuambil Lagi Hatiku,Kuambil Lagi Hatiku,2019,123.0,Drama
146140,tt9916622,Rodolpho Teóphilo - O Legado de um Pioneiro,Rodolpho Teóphilo - O Legado de um Pioneiro,2015,NaN,Documentary
146141,tt9916706,Dankyavar Danka,Dankyavar Danka,2013,NaN,Comedy
146142,tt9916730,6 Gunn,6 Gunn,2017,116.0,None
146143,tt9916754,Chico Albuquerque - Revelações,Chico Albuquerque - Revelações,2013,NaN,Documentary

In [6]:
pd.read_sql("SELECT * FROM movie_ratings ORDER BY movie_id;", conn)

        movie_id  averagerating  numvotes
0      tt0063540            7.0        77
1      tt0066787            7.2        43
2      tt0069049            6.9      4517
3      tt0069204            6.1        13
4      tt0100275            6.5       119
...          ...            ...       ...
73851  tt9913084            6.2         6
73852  tt9914286            8.7       136
73853  tt9914642            8.5         8
73854  tt9914942            6.6         5
73855  tt9916160            6.5        11

[73856 rows x 3 columns]

In [7]:
#########KEEP#########################

s = """
SELECT primary_title, runtime_minutes, genres, averagerating, numvotes 
FROM movie_basics
JOIN movie_ratings
USING(movie_id)
WHERE numvotes > 65000
ORDER BY numvotes DESC
;
"""
imdb = pd.read_sql(s, conn)
#######################################

In [8]:
imdb

,primary_title,runtime_minutes,genres,averagerating,numvotes
0,Inception,148.0,"Action,Adventure,Sci-Fi",8.8,1841066
1,The Dark Knight Rises,164.0,"Action,Thriller",8.4,1387769
2,Interstellar,169.0,"Adventure,Drama,Sci-Fi",8.6,1299334
3,Django Unchained,165.0,"Drama,Western",8.4,1211405
4,The Avengers,143.0,"Action,Adventure,Sci-Fi",8.1,1183655
...,...,...,...,...,...
905,Baahubali 2: The Conclusion,167.0,"Action,Drama",8.3,65656
906,The Sitter,81.0,Comedy,5.7,65575
907,The Iceman,106.0,"Biography,Crime,Drama",6.9,65571
908,Inside Job,109.0,"Crime,Documentary",8.3,65304
909,This Is Where I Leave You,103.0,"Comedy,Drama",6.6,65202

In [9]:
imdb.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 910 entries, 0 to 909
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   primary_title    910 non-null    object
 1   runtime_minutes  910 non-null    float64
 2   genres           910 non-null    object
 3   averagerating    910 non-null    float64
 4   numvotes         910 non-null    int64
dtypes: float64(2), int64(1), object(2)
memory usage: 35.7+ KB

In [10]:
imdb.dropna(inplace=True)

In [11]:
imdb.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 910 entries, 0 to 909
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   primary_title    910 non-null    object
 1   runtime_minutes  910 non-null    float64
 2   genres           910 non-null    object
 3   averagerating    910 non-null    float64
 4   numvotes         910 non-null    int64
dtypes: float64(2), int64(1), object(2)
memory usage: 42.7+ KB

In [12]:
imdb.head(60)

,primary_title,runtime_minutes,genres,averagerating,numvotes
0,Inception,148.0,"Action,Adventure,Sci-Fi",8.8,1841066
1,The Dark Knight Rises,164.0,"Action,Thriller",8.4,1387769
2,Interstellar,169.0,"Adventure,Drama,Sci-Fi",8.6,1299334
3,Django Unchained,165.0,"Drama,Western",8.4,1211405
4,The Avengers,143.0,"Action,Adventure,Sci-Fi",8.1,1183655
5,The Wolf of Wall Street,180.0,"Biography,Crime,Drama",8.2,1035358
6,Shutter Island,138.0,"Mystery,Thriller",8.1,1005960
7,Guardians of the Galaxy,121.0,"Action,Adventure,Comedy",8.1,948394
8,Deadpool,108.0,"Action,Adventure,Comedy",8.0,820847
9,The Hunger Games,142.0,"Action,Adventure,Sci-Fi",7.2,795227
10,Star Wars: Episode VII - The Force Awakens,136.0,"Action,Adventure,Fantasy",8.0,784780
11,Mad Max: Fury Road,120.0,"Action,Adventure,Sci-Fi",8.1,780910
12,Gone Girl,149.0,"Drama,Mystery,Thriller",8.1,761592
13,The Hobbit: An Unexpected Journey,169.0,"Adventure,Family,Fantasy",7.9,719629
14,Gravity,91.0,"Drama,Sci-Fi,Thriller",7.7,710018
15,Iron Man 3,130.0,"Action,Adventure,Sci-Fi",7.2,692794
16,Harry Potter and the Deathly Hallows: Part 2,130.0,"Adventure,Drama,Fantasy",8.1,691835
17,Thor,115.0,"Action,Adventure,Fantasy",7.0,683264
18,Toy Story 3,103.0,"Adventure,Animation,Comedy",8.3,682218
19,The Martian,144.0,"Adventure,Drama,Sci-Fi",8.0,680116
20,The Intouchables,112.0,"Biography,Comedy,Drama",8.5,677343
21,Avengers: Infinity War,149.0,"Action,Adventure,Sci-Fi",8.5,670926
22,Captain America: The First Avenger,124.0,"Action,Adventure,Sci-Fi",6.9,668137
23,Captain America: The Winter Soldier,136.0,"Action,Adventure,Sci-Fi",7.8,666252
24,Avengers: Age of Ultron,141.0,"Action,Adventure,Sci-Fi",7.3,665594
25,Iron Man 2,124.0,"Action,Adventure,Sci-Fi",7.0,657690
26,Black Swan,108.0,"Drama,Thriller",8.0,648854
27,Man of Steel,143.0,"Action,Adventure,Sci-Fi",7.1,647288
28,The Grand Budapest Hotel,99.0,"Adventure,Comedy,Crime",8.1,633604
29,The Revenant,156.0,"Action,Adventure,Biography",8.0,621193
30,Silver Linings Playbook,122.0,"Comedy,Drama,Romance",7.7,621018
31,The Imitation Game,114.0,"Biography,Drama,Thriller",8.0,620834
32,X-Men: Days of Future Past,132.0,"Action,Adventure,Sci-Fi",8.0,620079
33,Whiplash,106.0,"Drama,Music",8.5,616916
34,How to Train Your Dragon,98.0,"Action,Adventure,Animation",8.1,611299
35,X-Men: First Class,131.0,"Action,Adventure,Sci-Fi",7.7,608930
36,The King's Speech,118.0,"Biography,Drama,History",8.0,593629
37,Skyfall,143.0,"Action,Adventure,Thriller",7.8,592221
38,Captain America: Civil War,147.0,"Action,Adventure,Sci-Fi",7.8,583507
39,12 Years a Slave,134.0,"Biography,Drama,History",8.1,577301
40,Batman v Superman: Dawn of Justice,151.0,"Action,Adventure,Fantasy",6.5,576909
41,The Hunger Games: Catching Fire,146.0,"Action,Adventure,Sci-Fi",7.5,575455
42,The Social Network,120.0,"Biography,Drama",7.7,568578
43,The Hobbit: The Desolation of Smaug,161.0,"Adventure,Fantasy",7.8,565563
44,Logan,137.0,"Action,Drama,Sci-Fi",8.1,560270
45,World War Z,116.0,"Action,Adventure,Horror",7.0,553751
46,Now You See Me,115.0,"Crime,Mystery,Thriller",7.3,553156
47,Edge of Tomorrow,113.0,"Action,Sci-Fi",7.9,546284
48,Kingsman: The Secret Service,129.0,"Action,Adventure,Comedy",7.7,544510
49,Thor: The Dark World,112.0,"Action,Adventure,Fantasy",6.9,540996
50,Jurassic World,124.0,"Action,Adventure,Sci-Fi",7.0,539338
51,Prometheus,124.0,"Adventure,Mystery,Sci-Fi",7.0,538720
52,Ted,106.0,"Comedy,Fantasy",6.9,538367
53,Inside Out,95.0,"Adventure,Animation,Comedy",8.2,536181
54,Life of Pi,127.0,"Adventure,Drama,Fantasy",7.9,535836
55,Argo,120.0,"Biography,Drama,Thriller",7.7,534683
56,Suicide Squad,123.0,"Action,Adventure,Fantasy",6.0,533039
57,Prisoners,153.0,"Crime,Drama,Mystery",8.1,526273
58,The Amazing Spider-Man,136.0,"Action,Adventure,Sci-Fi",7.0,525632
59,Drive,100.0,"Crime,Drama",7.8,521495

In [13]:
imdb.describe()

       runtime_minutes  averagerating      numvotes
count       910.000000     910.000000  9.100000e+02
mean        114.015385       6.809121  2.040407e+05
std          18.827682       0.837996  1.791473e+05
min          80.000000       1.600000  6.520200e+04
25%         101.000000       6.300000  9.016400e+04
50%         111.000000       6.800000  1.381810e+05
75%         124.000000       7.400000  2.394260e+05
max         321.000000       9.300000  1.841066e+06

## Data Preparation
Describe and justify the process for preparing the data for analysis.

Questions to consider:

* Were there variables you dropped or created?
* How did you address missing values or outliers?
* Why are these choices appropriate given the data and the business problem?

In [14]:
imdb.value_counts()

primary_title                               runtime_minutes  genres                      averagerating  numvotes
xXx: Return of Xander Cage                  107.0            Action,Adventure,Thriller   5.2            77976       1
Horns                                       120.0            Crime,Drama,Fantasy         6.5            70040       1
Inception                                   148.0            Action,Adventure,Sci-Fi     8.8            1841066     1
Incendies                                   131.0            Drama,Mystery,War           8.3            124156      1
In the Heart of the Sea                     122.0            Action,Adventure,Biography  6.9            108628      1
                                                                                                                   ..
Star Wars: Episode VII - The Force Awakens  136.0            Action,Adventure,Fantasy    8.0            784780      1
Star Trek Into Darkness                     132.0            Action,Adventure,Sci-Fi     7.7            445535      1
Star Trek Beyond                            122.0            Action,Adventure,Sci-Fi     7.1            209844      1
St. Vincent                                 102.0            Comedy,Drama                7.3            89372       1
10 Cloverfield Lane                         103.0            Drama,Horror,Mystery        7.2            260383      1
Length: 910, dtype: int64

In [15]:
imdb.duplicated().value_counts()

False    910
dtype: int64

In [16]:
####SELECT FROM WHERE
    ###Genre LIKE '%Action%'

In [17]:
###DEL combined_df = pd.concat([x, y], axis=1, join='inner')

In [18]:
###  combined_df

# ################################################################

In [19]:
##TEST TEST#########---HIGHEST GROSSING ACTOR/ACTRESS---#####################

q = """
SELECT primary_title, runtime_minutes, genres, category, primary_name, averagerating, numvotes 
FROM principals
JOIN movie_ratings
USING (movie_id)
JOIN movie_basics
USING (movie_id)
JOIN persons
USING (person_id)
WHERE category = "actress"
OR category = "actor"
ORDER BY numvotes DESC;
"""
imdb2 = pd.read_sql(q, conn)
#######################################

In [20]:
#### add where num votes > 25000

In [21]:
imdb2.head(60)

,primary_title,runtime_minutes,genres,category,primary_name,averagerating,numvotes
0,Inception,148.0,"Action,Adventure,Sci-Fi",actor,Leonardo DiCaprio,8.8,1841066
1,Inception,148.0,"Action,Adventure,Sci-Fi",actor,Joseph Gordon-Levitt,8.8,1841066
2,Inception,148.0,"Action,Adventure,Sci-Fi",actress,Ellen Page,8.8,1841066
3,Inception,148.0,"Action,Adventure,Sci-Fi",actor,Ken Watanabe,8.8,1841066
4,The Dark Knight Rises,164.0,"Action,Thriller",actor,Christian Bale,8.4,1387769
5,The Dark Knight Rises,164.0,"Action,Thriller",actor,Tom Hardy,8.4,1387769
6,The Dark Knight Rises,164.0,"Action,Thriller",actress,Anne Hathaway,8.4,1387769
7,The Dark Knight Rises,164.0,"Action,Thriller",actor,Gary Oldman,8.4,1387769
8,Interstellar,169.0,"Adventure,Drama,Sci-Fi",actor,Matthew McConaughey,8.6,1299334
9,Interstellar,169.0,"Adventure,Drama,Sci-Fi",actress,Anne Hathaway,8.6,1299334
10,Interstellar,169.0,"Adventure,Drama,Sci-Fi",actress,Jessica Chastain,8.6,1299334
11,Interstellar,169.0,"Adventure,Drama,Sci-Fi",actress,Mackenzie Foy,8.6,1299334
12,Django Unchained,165.0,"Drama,Western",actor,Jamie Foxx,8.4,1211405
13,Django Unchained,165.0,"Drama,Western",actor,Christoph Waltz,8.4,1211405
14,Django Unchained,165.0,"Drama,Western",actor,Leonardo DiCaprio,8.4,1211405
15,Django Unchained,165.0,"Drama,Western",actress,Kerry Washington,8.4,1211405
16,The Avengers,143.0,"Action,Adventure,Sci-Fi",actor,Robert Downey Jr.,8.1,1183655
17,The Avengers,143.0,"Action,Adventure,Sci-Fi",actor,Chris Evans,8.1,1183655
18,The Avengers,143.0,"Action,Adventure,Sci-Fi",actress,Scarlett Johansson,8.1,1183655
19,The Avengers,143.0,"Action,Adventure,Sci-Fi",actor,Jeremy Renner,8.1,1183655
20,The Wolf of Wall Street,180.0,"Biography,Crime,Drama",actor,Leonardo DiCaprio,8.2,1035358
21,The Wolf of Wall Street,180.0,"Biography,Crime,Drama",actor,Jonah Hill,8.2,1035358
22,The Wolf of Wall Street,180.0,"Biography,Crime,Drama",actress,Margot Robbie,8.2,1035358
23,The Wolf of Wall Street,180.0,"Biography,Crime,Drama",actor,Matthew McConaughey,8.2,1035358
24,Shutter Island,138.0,"Mystery,Thriller",actor,Leonardo DiCaprio,8.1,1005960
25,Shutter Island,138.0,"Mystery,Thriller",actress,Emily Mortimer,8.1,1005960
26,Shutter Island,138.0,"Mystery,Thriller",actor,Mark Ruffalo,8.1,1005960
27,Shutter Island,138.0,"Mystery,Thriller",actor,Ben Kingsley,8.1,1005960
28,Guardians of the Galaxy,121.0,"Action,Adventure,Comedy",actor,Chris Pratt,8.1,948394
29,Guardians of the Galaxy,121.0,"Action,Adventure,Comedy",actor,Vin Diesel,8.1,948394
30,Guardians of the Galaxy,121.0,"Action,Adventure,Comedy",actor,Bradley Cooper,8.1,948394
31,Guardians of the Galaxy,121.0,"Action,Adventure,Comedy",actress,Zoe Saldana,8.1,948394
32,Deadpool,108.0,"Action,Adventure,Comedy",actor,Ryan Reynolds,8.0,820847
33,Deadpool,108.0,"Action,Adventure,Comedy",actress,Morena Baccarin,8.0,820847
34,Deadpool,108.0,"Action,Adventure,Comedy",actor,T.J. Miller,8.0,820847
35,Deadpool,108.0,"Action,Adventure,Comedy",actor,Ed Skrein,8.0,820847
36,The Hunger Games,142.0,"Action,Adventure,Sci-Fi",actress,Jennifer Lawrence,7.2,795227
37,The Hunger Games,142.0,"Action,Adventure,Sci-Fi",actor,Josh Hutcherson,7.2,795227
38,The Hunger Games,142.0,"Action,Adventure,Sci-Fi",actor,Liam Hemsworth,7.2,795227
39,The Hunger Games,142.0,"Action,Adventure,Sci-Fi",actor,Stanley Tucci,7.2,795227
40,Star Wars: Episode VII - The Force Awakens,136.0,"Action,Adventure,Fantasy",actress,Daisy Ridley,8.0,784780
41,Star Wars: Episode VII - The Force Awakens,136.0,"Action,Adventure,Fantasy",actor,John Boyega,8.0,784780
42,Star Wars: Episode VII - The Force Awakens,136.0,"Action,Adventure,Fantasy",actor,Oscar Isaac,8.0,784780
43,Star Wars: Episode VII - The Force Awakens,136.0,"Action,Adventure,Fantasy",actor,Domhnall Gleeson,8.0,784780
44,Mad Max: Fury Road,120.0,"Action,Adventure,Sci-Fi",actor,Tom Hardy,8.1,780910
45,Mad Max: Fury Road,120.0,"Action,Adventure,Sci-Fi",actress,Charlize Theron,8.1,780910
46,Mad Max: Fury Road,120.0,"Action,Adventure,Sci-Fi",actor,Nicholas Hoult,8.1,780910
47,Mad Max: Fury Road,120.0,"Action,Adventure,Sci-Fi",actress,Zoë Kravitz,8.1,780910
48,Gone Girl,149.0,"Drama,Mystery,Thriller",actor,Ben Affleck,8.1,761592
49,Gone Girl,149.0,"Drama,Mystery,Thriller",actress,Rosamund Pike,8.1,761592
50,Gone Girl,149.0,"Drama,Mystery,Thriller",actor,Neil Patrick Harris,8.1,761592
51,Gone Girl,149.0,"Drama,Mystery,Thriller",actor,Tyler Perry,8.1,761592
52,The Hobbit: An Unexpected Journey,169.0,"Adventure,Family,Fantasy",actor,Martin Freeman,7.9,719629
53,The Hobbit: An Unexpected Journey,169.0,"Adventure,Family,Fantasy",actor,Ian McKellen,7.9,719629
54,The Hobbit: An Unexpected Journey,169.0,"Adventure,Family,Fantasy",actor,Richard Armitage,7.9,719629
55,The Hobbit: An Unexpected Journey,169.0,"Adventure,Family,Fantasy",actor,Andy Serkis,7.9,719629
56,Gravity,91.0,"Drama,Sci-Fi,Thriller",actress,Sandra Bullock,7.7,710018
57,Gravity,91.0,"Drama,Sci-Fi,Thriller",actor,George Clooney,7.7,710018
58,Gravity,91.0,"Drama,Sci-Fi,Thriller",actor,Ed Harris,7.7,710018
59,Gravity,91.0,"Drama,Sci-Fi,Thriller",actor,Orto Ignatiussen,7.7,710018

In [22]:
imdb2

,primary_title,runtime_minutes,genres,category,primary_name,averagerating,numvotes
0,Inception,148.0,"Action,Adventure,Sci-Fi",actor,Leonardo DiCaprio,8.8,1841066
1,Inception,148.0,"Action,Adventure,Sci-Fi",actor,Joseph Gordon-Levitt,8.8,1841066
2,Inception,148.0,"Action,Adventure,Sci-Fi",actress,Ellen Page,8.8,1841066
3,Inception,148.0,"Action,Adventure,Sci-Fi",actor,Ken Watanabe,8.8,1841066
4,The Dark Knight Rises,164.0,"Action,Thriller",actor,Christian Bale,8.4,1387769
...,...,...,...,...,...,...,...
248295,Casting Chloe,NaN,"Comedy,Drama",actress,Sarah Jones Dittmeier,8.2,5
248296,Casting Chloe,NaN,"Comedy,Drama",actress,Annabelle Fox,8.2,5
248297,American Dope: Acid Dreams,53.0,Documentary,actor,Alan Bradley,8.2,5
248298,American Dope: Acid Dreams,53.0,Documentary,actor,Michael Levine,8.2,5
248299,American Dope: Acid Dreams,53.0,Documentary,actor,Tim Scully,8.2,5

In [23]:
####TEST####
imdb2['primary_name'].value_counts()

Eric Roberts           122
Brahmanandam            74
Prakash Raj             74
Tom Sizemore            61
Michael Madsen          59
                      ...
Allison Ochmanek         1
Aaron Springfield        1
Andrea Pavoni Belli      1
Andrus Albrecht          1
Manuel Gomes             1
Name: primary_name, Length: 142527, dtype: int64

In [24]:
####TEST####
imdb2['genres'].value_counts().head(20)

Drama                   48535
Comedy                  24363
Horror                  12110
Comedy,Drama            11008
Thriller                 6608
Drama,Romance            6301
Documentary              6247
Comedy,Romance           5339
Comedy,Drama,Romance     5056
Action                   4502
Horror,Thriller          4225
Drama,Thriller           4140
Romance                  3094
Comedy,Horror            2551
Action,Crime,Drama       2399
Crime,Drama,Thriller     2093
Crime,Drama              2079
Family                   2015
Drama,Family             1980
Action,Drama             1738
Name: genres, dtype: int64

# 2 BOX OFFICE MOJO

In [25]:
##Loading up the first dataframe, BOX OFFICE MOJO, with Pandas.Importing Data
# Import the file and print the first 5 rows
bom = pd.read_csv("zippedData/bom.movie_gross.csv.gz")
bom

,title,studio,domestic_gross,foreign_gross,year
0,Toy Story 3,BV,415000000.0,652000000,2010
1,Alice in Wonderland (2010),BV,334200000.0,691300000,2010
2,Harry Potter and the Deathly Hallows Part 1,WB,296000000.0,664300000,2010
3,Inception,WB,292600000.0,535700000,2010
4,Shrek Forever After,P/DW,238700000.0,513900000,2010
...,...,...,...,...,...
3382,The Quake,Magn.,6200.0,NaN,2018
3383,Edward II (2018 re-release),FM,4800.0,NaN,2018
3384,El Pacto,Sony,2500.0,NaN,2018
3385,The Swan,Synergetic,2400.0,NaN,2018
3386,An Actor Prepares,Grav.,1700.0,NaN,2018

In [26]:
bom.info()
### CHANGE FOREIGN GROSS TO FLOAT

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3387 entries, 0 to 3386
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   title           3387 non-null   object
 1   studio          3382 non-null   object
 2   domestic_gross  3359 non-null   float64
 3   foreign_gross   2037 non-null   object
 4   year            3387 non-null   int64
dtypes: float64(1), int64(1), object(3)
memory usage: 132.4+ KB

In [27]:
## bom['foreign_gross'].astype(float)
##Gives Error: could not convert string to float: '1,131.6'

In [28]:
## bom['foreign_gross'].astype(int)
##Gives Error: cannot convert float NaN to integer

In [29]:
### sorting the values by domestic gross, we see that the foreign gross is off for 3 of the top results and for Furious 7.
bom.sort_values(by=['domestic_gross'],ascending=False)

,title,studio,domestic_gross,foreign_gross,year
1872,Star Wars: The Force Awakens,BV,936700000.0,"1,131.6",2015
3080,Black Panther,BV,700100000.0,646900000,2018
3079,Avengers: Infinity War,BV,678800000.0,"1,369.5",2018
1873,Jurassic World,Uni.,652300000.0,"1,019.4",2015
727,Marvel's The Avengers,BV,623400000.0,895500000,2012
...,...,...,...,...,...
1975,Surprise - Journey To The West,AR,NaN,49600000,2015
2392,Finding Mr. Right 2,CL,NaN,114700000,2016
2468,Solace,LGP,NaN,22400000,2016
2595,Viral,W/Dim.,NaN,552000,2016
2825,Secret Superstar,NaN,NaN,122000000,2017

In [30]:
### sorting the values by foreign gross, we see that the top 5 results are wildly popular franchises with a little over $1k gross.
bom.sort_values(by=['foreign_gross'])

,title,studio,domestic_gross,foreign_gross,year
2760,The Fate of the Furious,Uni.,226000000.0,"1,010.0",2017
1873,Jurassic World,Uni.,652300000.0,"1,019.4",2015
1872,Star Wars: The Force Awakens,BV,936700000.0,"1,131.6",2015
1874,Furious 7,Uni.,353000000.0,"1,163.0",2015
3079,Avengers: Infinity War,BV,678800000.0,"1,369.5",2018
...,...,...,...,...,...
3382,The Quake,Magn.,6200.0,NaN,2018
3383,Edward II (2018 re-release),FM,4800.0,NaN,2018
3384,El Pacto,Sony,2500.0,NaN,2018
3385,The Swan,Synergetic,2400.0,NaN,2018
3386,An Actor Prepares,Grav.,1700.0,NaN,2018

In [31]:
## REPLACE the erroneous values with more realistic ones.  The five entries were most likely meant to contain billions in gross.
bom['foreign_gross'] = bom['foreign_gross'].replace(['1,010.0','1,019.4','1,131.6', '1,163.0','1,369.5'], ['1010000000', '1019000000', '1131000000', '1163000000', '1369000000'])

In [32]:
#check to see if the values changed
bom.sort_values(by=['domestic_gross'],ascending=False)

,title,studio,domestic_gross,foreign_gross,year
1872,Star Wars: The Force Awakens,BV,936700000.0,1131000000,2015
3080,Black Panther,BV,700100000.0,646900000,2018
3079,Avengers: Infinity War,BV,678800000.0,1369000000,2018
1873,Jurassic World,Uni.,652300000.0,1019000000,2015
727,Marvel's The Avengers,BV,623400000.0,895500000,2012
...,...,...,...,...,...
1975,Surprise - Journey To The West,AR,NaN,49600000,2015
2392,Finding Mr. Right 2,CL,NaN,114700000,2016
2468,Solace,LGP,NaN,22400000,2016
2595,Viral,W/Dim.,NaN,552000,2016
2825,Secret Superstar,NaN,NaN,122000000,2017

In [33]:
bom.dropna(inplace=True)

In [34]:
bom

,title,studio,domestic_gross,foreign_gross,year
0,Toy Story 3,BV,415000000.0,652000000,2010
1,Alice in Wonderland (2010),BV,334200000.0,691300000,2010
2,Harry Potter and the Deathly Hallows Part 1,WB,296000000.0,664300000,2010
3,Inception,WB,292600000.0,535700000,2010
4,Shrek Forever After,P/DW,238700000.0,513900000,2010
...,...,...,...,...,...
3275,I Still See You,LGF,1400.0,1500000,2018
3286,The Catcher Was a Spy,IFC,725000.0,229000,2018
3309,Time Freak,Grindstone,10000.0,256000,2018
3342,Reign of Judges: Title of Liberty - Concept Short,Darin Southa,93200.0,5200,2018
3353,Antonio Lopez 1970: Sex Fashion & Disco,FM,43200.0,30000,2018

In [35]:
#### convert 'domestic gross' column from object to float########
bom['domestic_gross'] = bom['domestic_gross'].astype(int)

In [36]:
#### convert 'foreign gross' column from object to float########
bom['foreign_gross'] = bom['foreign_gross'].astype(int)

In [37]:
bom.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2007 entries, 0 to 3353
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   title           2007 non-null   object
 1   studio          2007 non-null   object
 2   domestic_gross  2007 non-null   int32
 3   foreign_gross   2007 non-null   int32
 4   year            2007 non-null   int64
dtypes: int32(2), int64(1), object(2)
memory usage: 78.4+ KB

In [38]:
bom['total_gross'] = bom['domestic_gross'] + bom['foreign_gross']

In [39]:
bom

,title,studio,domestic_gross,foreign_gross,year,total_gross
0,Toy Story 3,BV,415000000,652000000,2010,1067000000
1,Alice in Wonderland (2010),BV,334200000,691300000,2010,1025500000
2,Harry Potter and the Deathly Hallows Part 1,WB,296000000,664300000,2010,960300000
3,Inception,WB,292600000,535700000,2010,828300000
4,Shrek Forever After,P/DW,238700000,513900000,2010,752600000
...,...,...,...,...,...,...
3275,I Still See You,LGF,1400,1500000,2018,1501400
3286,The Catcher Was a Spy,IFC,725000,229000,2018,954000
3309,Time Freak,Grindstone,10000,256000,2018,266000
3342,Reign of Judges: Title of Liberty - Concept Short,Darin Southa,93200,5200,2018,98400
3353,Antonio Lopez 1970: Sex Fashion & Disco,FM,43200,30000,2018,73200

In [40]:
bom.sort_values(by=['total_gross'],ascending=False)

,title,studio,domestic_gross,foreign_gross,year,total_gross
1872,Star Wars: The Force Awakens,BV,936700000,1131000000,2015,2067700000
3079,Avengers: Infinity War,BV,678800000,1369000000,2018,2047800000
1873,Jurassic World,Uni.,652300000,1019000000,2015,1671300000
727,Marvel's The Avengers,BV,623400000,895500000,2012,1518900000
1874,Furious 7,Uni.,353000000,1163000000,2015,1516000000
...,...,...,...,...,...,...
711,I'm Glad My Mother is Alive,Strand,8700,13200,2011,21900
322,The Thorn in the Heart,Osci.,7400,10500,2010,17900
1110,Cirkus Columbia,Strand,3500,9500,2012,13000
715,Aurora,CGld,5700,5100,2011,10800
721,To Die Like a Man,Strand,4000,900,2011,4900

In [41]:
bom = bom.drop(['studio', 'year'], axis=1)

In [42]:
bom.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2007 entries, 0 to 3353
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   title           2007 non-null   object
 1   domestic_gross  2007 non-null   int32
 2   foreign_gross   2007 non-null   int32
 3   total_gross     2007 non-null   int32
dtypes: int32(3), object(1)
memory usage: 54.9+ KB

In [43]:
bom

,title,domestic_gross,foreign_gross,total_gross
0,Toy Story 3,415000000,652000000,1067000000
1,Alice in Wonderland (2010),334200000,691300000,1025500000
2,Harry Potter and the Deathly Hallows Part 1,296000000,664300000,960300000
3,Inception,292600000,535700000,828300000
4,Shrek Forever After,238700000,513900000,752600000
...,...,...,...,...
3275,I Still See You,1400,1500000,1501400
3286,The Catcher Was a Spy,725000,229000,954000
3309,Time Freak,10000,256000,266000
3342,Reign of Judges: Title of Liberty - Concept Short,93200,5200,98400
3353,Antonio Lopez 1970: Sex Fashion & Disco,43200,30000,73200

In [44]:
bom.sort_values(by=['total_gross'],ascending=False).head(60)

,title,domestic_gross,foreign_gross,total_gross
1872,Star Wars: The Force Awakens,936700000,1131000000,2067700000
3079,Avengers: Infinity War,678800000,1369000000,2047800000
1873,Jurassic World,652300000,1019000000,1671300000
727,Marvel's The Avengers,623400000,895500000,1518900000
1874,Furious 7,353000000,1163000000,1516000000
1875,Avengers: Age of Ultron,459000000,946400000,1405400000
3080,Black Panther,700100000,646900000,1347000000
328,Harry Potter and the Deathly Hallows Part 2,381000000,960500000,1341500000
2758,Star Wars: The Last Jedi,620200000,712400000,1332600000
3081,Jurassic World: Fallen Kingdom,417700000,891800000,1309500000
1127,Frozen,400700000,875700000,1276400000
2759,Beauty and the Beast (2017),504000000,759500000,1263500000
3082,Incredibles 2,608600000,634200000,1242800000
2760,The Fate of the Furious,226000000,1010000000,1236000000
1128,Iron Man 3,409000000,805800000,1214800000
1876,Minions,336000000,823400000,1159400000
2322,Captain America: Civil War,408100000,745200000,1153300000
3083,Aquaman,335100000,812700000,1147800000
329,Transformers: Dark of the Moon,352400000,771400000,1123800000
728,Skyfall,304400000,804200000,1108600000
1477,Transformers: Age of Extinction,245400000,858600000,1104000000
729,The Dark Knight Rises,448100000,636800000,1084900000
0,Toy Story 3,415000000,652000000,1067000000
2323,Rogue One: A Star Wars Story,532200000,523900000,1056100000
330,Pirates of the Caribbean: On Stranger Tides,241100000,804600000,1045700000
2761,Despicable Me 3,264600000,770200000,1034800000
2324,Finding Dory,486300000,542300000,1028600000
1,Alice in Wonderland (2010),334200000,691300000,1025500000
2325,Zootopia,341300000,682500000,1023800000
730,The Hobbit: An Unexpected Journey,303000000,718100000,1021100000
1129,Despicable Me 2,368100000,602700000,970800000
2326,The Jungle Book (2016),364000000,602500000,966500000
2762,Jumanji: Welcome to the Jungle,404500000,557600000,962100000
2,Harry Potter and the Deathly Hallows Part 1,296000000,664300000,960300000
1130,The Hobbit: The Desolation of Smaug,258399999,700000000,958399999
1478,The Hobbit: The Battle of the Five Armies,255100000,700900000,956000000
3084,Bohemian Rhapsody,216400000,687200000,903600000
1877,Spectre,200100000,680600000,880700000
2763,Spider-Man: Homecoming,334200000,546000000,880200000
731,Ice Age: Continental Drift,161300000,715900000,877200000
2327,The Secret Life of Pets,368400000,507100000,875500000
2328,Batman v Superman: Dawn of Justice,330400000,543300000,873700000
2764,Wolf Warrior 2,2700000,867600000,870300000
1131,The Hunger Games: Catching Fire,424700000,440300000,865000000
2765,Guardians of the Galaxy Vol. 2,389800000,473900000,863700000
1878,Inside Out,356500000,501100000,857600000
3085,Venom (2018),213500000,641500000,855000000
2766,Thor: Ragnarok,315100000,538900000,854000000
732,The Twilight Saga: Breaking Dawn Part 2,292300000,537400000,829700000
3,Inception,292600000,535700000,828300000
2767,Wonder Woman,412600000,409300000,821900000
2329,Fantastic Beasts and Where To Find Them,234000000,580000000,814000000
2768,Coco,209700000,597400000,807100000
2769,Pirates of the Caribbean: Dead Men Tell No Tales,172600000,622300000,794900000
3086,Mission: Impossible - Fallout,220200000,571000000,791200000
1132,Fast & Furious 6,238700000,550000000,788700000
2330,Deadpool,363100000,420000000,783100000
3087,Deadpool 2,318500000,460500000,779000000
1479,Guardians of the Galaxy,333200000,440200000,773400000
1480,Maleficent,241400000,517100000,758500000

In [45]:
bom.describe()

       domestic_gross  foreign_gross   total_gross
count    2.007000e+03   2.007000e+03  2.007000e+03
mean     4.701984e+07   7.862646e+07  1.256463e+08
std      8.162689e+07   1.480804e+08  2.211996e+08
min      4.000000e+02   6.000000e+02  4.900000e+03
25%      6.700000e+05   4.000000e+06  8.239000e+06
50%      1.670000e+07   1.970000e+07  4.240000e+07
75%      5.605000e+07   7.775000e+07  1.337500e+08
max      9.367000e+08   1.369000e+09  2.067700e+09

In [46]:
bom.columns

Index(['title', 'domestic_gross', 'foreign_gross', 'total_gross'], dtype='object')

In [47]:
bom.isna().sum()

title             0
domestic_gross    0
foreign_gross     0
total_gross       0
dtype: int64

In [48]:
bom.dtypes

###change foreign_gross into float

title             object
domestic_gross     int32
foreign_gross      int32
total_gross        int32
dtype: object

In [49]:
bom.head(20)

,title,domestic_gross,foreign_gross,total_gross
0,Toy Story 3,415000000,652000000,1067000000
1,Alice in Wonderland (2010),334200000,691300000,1025500000
2,Harry Potter and the Deathly Hallows Part 1,296000000,664300000,960300000
3,Inception,292600000,535700000,828300000
4,Shrek Forever After,238700000,513900000,752600000
5,The Twilight Saga: Eclipse,300500000,398000000,698500000
6,Iron Man 2,312400000,311500000,623900000
7,Tangled,200800000,391000000,591800000
8,Despicable Me,251500000,291600000,543100000
9,How to Train Your Dragon,217600000,277300000,494900000
10,Clash of the Titans (2010),163200000,330000000,493200000
11,The Chronicles of Narnia: The Voyage of the Da...,104400000,311300000,415700000
12,The King's Speech,135500000,275400000,410900000
13,Tron Legacy,172100000,228000000,400100000
14,The Karate Kid,176600000,182500000,359100000
15,Prince of Persia: The Sands of Time,90800000,245600000,336400000
16,Black Swan,107000000,222400000,329400000
17,Megamind,148400000,173500000,321900000
18,Robin Hood,105300000,216400000,321700000
19,The Last Airbender,131800000,187900000,319700000

In [50]:
bom.shape

(2007, 4)

## JOINING DATAFRAMES

In [51]:
bom.set_index('title', inplace=True)

In [52]:
bom.head()

,domestic_gross,foreign_gross,total_gross
title,,,
Toy Story 3,415000000,652000000,1067000000
Alice in Wonderland (2010),334200000,691300000,1025500000
Harry Potter and the Deathly Hallows Part 1,296000000,664300000,960300000
Inception,292600000,535700000,828300000
Shrek Forever After,238700000,513900000,752600000

In [53]:
imdb.set_index('primary_title', inplace=True)

In [54]:
imdb

,runtime_minutes,genres,averagerating,numvotes
primary_title,,,,
Inception,148.0,"Action,Adventure,Sci-Fi",8.8,1841066
The Dark Knight Rises,164.0,"Action,Thriller",8.4,1387769
Interstellar,169.0,"Adventure,Drama,Sci-Fi",8.6,1299334
Django Unchained,165.0,"Drama,Western",8.4,1211405
The Avengers,143.0,"Action,Adventure,Sci-Fi",8.1,1183655
...,...,...,...,...
Baahubali 2: The Conclusion,167.0,"Action,Drama",8.3,65656
The Sitter,81.0,Comedy,5.7,65575
The Iceman,106.0,"Biography,Crime,Drama",6.9,65571
Inside Job,109.0,"Crime,Documentary",8.3,65304
This Is Where I Leave You,103.0,"Comedy,Drama",6.6,65202

In [55]:
joined_df = imdb.join(bom, how='inner')

joined_df

,runtime_minutes,genres,averagerating,numvotes,domestic_gross,foreign_gross,total_gross
Inception,148.0,"Action,Adventure,Sci-Fi",8.8,1841066,292600000,535700000,828300000
The Dark Knight Rises,164.0,"Action,Thriller",8.4,1387769,448100000,636800000,1084900000
Interstellar,169.0,"Adventure,Drama,Sci-Fi",8.6,1299334,188000000,489400000,677400000
Django Unchained,165.0,"Drama,Western",8.4,1211405,162800000,262600000,425400000
The Wolf of Wall Street,180.0,"Biography,Crime,Drama",8.2,1035358,116900000,275100000,392000000
...,...,...,...,...,...,...,...
What to Expect When You're Expecting,110.0,"Comedy,Drama,Romance",5.7,65890,41200000,43200000,84400000
Dark Skies,97.0,"Horror,Sci-Fi,Thriller",6.3,65754,17400000,9000000,26400000
Baahubali 2: The Conclusion,167.0,"Action,Drama",8.3,65656,20200000,234000000,254200000
The Sitter,81.0,Comedy,5.7,65575,30400000,4500000,34900000
Inside Job,109.0,"Crime,Documentary",8.3,65304,4300000,3600000,7900000

In [56]:
joined_df.sort_values(by=['numvotes'], ascending=False).head(60)

,runtime_minutes,genres,averagerating,numvotes,domestic_gross,foreign_gross,total_gross
Inception,148.0,"Action,Adventure,Sci-Fi",8.8,1841066,292600000,535700000,828300000
The Dark Knight Rises,164.0,"Action,Thriller",8.4,1387769,448100000,636800000,1084900000
Interstellar,169.0,"Adventure,Drama,Sci-Fi",8.6,1299334,188000000,489400000,677400000
Django Unchained,165.0,"Drama,Western",8.4,1211405,162800000,262600000,425400000
The Wolf of Wall Street,180.0,"Biography,Crime,Drama",8.2,1035358,116900000,275100000,392000000
Shutter Island,138.0,"Mystery,Thriller",8.1,1005960,128000000,166800000,294800000
Guardians of the Galaxy,121.0,"Action,Adventure,Comedy",8.1,948394,333200000,440200000,773400000
Deadpool,108.0,"Action,Adventure,Comedy",8.0,820847,363100000,420000000,783100000
The Hunger Games,142.0,"Action,Adventure,Sci-Fi",7.2,795227,408000000,286400000,694400000
Mad Max: Fury Road,120.0,"Action,Adventure,Sci-Fi",8.1,780910,153600000,224800000,378400000
Gone Girl,149.0,"Drama,Mystery,Thriller",8.1,761592,167800000,201600000,369400000
The Hobbit: An Unexpected Journey,169.0,"Adventure,Family,Fantasy",7.9,719629,303000000,718100000,1021100000
Gravity,91.0,"Drama,Sci-Fi,Thriller",7.7,710018,274100000,449100000,723200000
Iron Man 3,130.0,"Action,Adventure,Sci-Fi",7.2,692794,409000000,805800000,1214800000
Thor,115.0,"Action,Adventure,Fantasy",7.0,683264,181000000,268300000,449300000
Toy Story 3,103.0,"Adventure,Animation,Comedy",8.3,682218,415000000,652000000,1067000000
The Martian,144.0,"Adventure,Drama,Sci-Fi",8.0,680116,228400000,401700000,630100000
Avengers: Infinity War,149.0,"Action,Adventure,Sci-Fi",8.5,670926,678800000,1369000000,2047800000
Captain America: The First Avenger,124.0,"Action,Adventure,Sci-Fi",6.9,668137,176700000,193900000,370600000
Captain America: The Winter Soldier,136.0,"Action,Adventure,Sci-Fi",7.8,666252,259800000,454500000,714300000
Avengers: Age of Ultron,141.0,"Action,Adventure,Sci-Fi",7.3,665594,459000000,946400000,1405400000
Iron Man 2,124.0,"Action,Adventure,Sci-Fi",7.0,657690,312400000,311500000,623900000
Black Swan,108.0,"Drama,Thriller",8.0,648854,107000000,222400000,329400000
Man of Steel,143.0,"Action,Adventure,Sci-Fi",7.1,647288,291000000,377000000,668000000
The Grand Budapest Hotel,99.0,"Adventure,Comedy,Crime",8.1,633604,59300000,115500000,174800000
The Revenant,156.0,"Action,Adventure,Biography",8.0,621193,183600000,349300000,532900000
Silver Linings Playbook,122.0,"Comedy,Drama,Romance",7.7,621018,132100000,104300000,236400000
The Imitation Game,114.0,"Biography,Drama,Thriller",8.0,620834,91100000,142400000,233500000
X-Men: Days of Future Past,132.0,"Action,Adventure,Sci-Fi",8.0,620079,233900000,513900000,747800000
Whiplash,106.0,"Drama,Music",8.5,616916,13100000,35900000,49000000
How to Train Your Dragon,98.0,"Action,Adventure,Animation",8.1,611299,217600000,277300000,494900000
X-Men: First Class,131.0,"Action,Adventure,Sci-Fi",7.7,608930,146400000,207200000,353600000
The King's Speech,118.0,"Biography,Drama,History",8.0,593629,135500000,275400000,410900000
Skyfall,143.0,"Action,Adventure,Thriller",7.8,592221,304400000,804200000,1108600000
Captain America: Civil War,147.0,"Action,Adventure,Sci-Fi",7.8,583507,408100000,745200000,1153300000
12 Years a Slave,134.0,"Biography,Drama,History",8.1,577301,56700000,131100000,187800000
Batman v Superman: Dawn of Justice,151.0,"Action,Adventure,Fantasy",6.5,576909,330400000,543300000,873700000
The Hunger Games: Catching Fire,146.0,"Action,Adventure,Sci-Fi",7.5,575455,424700000,440300000,865000000
The Social Network,120.0,"Biography,Drama",7.7,568578,97000000,128000000,225000000
The Hobbit: The Desolation of Smaug,161.0,"Adventure,Fantasy",7.8,565563,258399999,700000000,958399999
World War Z,116.0,"Action,Adventure,Horror",7.0,553751,202400000,337600000,540000000
Now You See Me,115.0,"Crime,Mystery,Thriller",7.3,553156,117700000,234000000,351700000
Edge of Tomorrow,113.0,"Action,Sci-Fi",7.9,546284,100200000,270300000,370500000
Kingsman: The Secret Service,129.0,"Action,Adventure,Comedy",7.7,544510,128300000,286100000,414400000
Thor: The Dark World,112.0,"Action,Adventure,Fantasy",6.9,540996,206400000,438200000,644600000
Jurassic World,124.0,"Action,Adventure,Sci-Fi",7.0,539338,652300000,1019000000,1671300000
Prometheus,124.0,"Adventure,Mystery,Sci-Fi",7.0,538720,126500000,276900000,403400000
Ted,106.0,"Comedy,Fantasy",6.9,538367,218800000,330600000,549400000
Inside Out,95.0,"Adventure,Animation,Comedy",8.2,536181,356500000,501100000,857600000
Life of Pi,127.0,"Adventure,Drama,Fantasy",7.9,535836,125000000,484000000,609000000
Argo,120.0,"Biography,Drama,Thriller",7.7,534683,136000000,96300000,232300000
Suicide Squad,123.0,"Action,Adventure,Fantasy",6.0,533039,325100000,421700000,746800000
Prisoners,153.0,"Crime,Drama,Mystery",8.1,526273,61000000,61100000,122100000
The Amazing Spider-Man,136.0,"Action,Adventure,Sci-Fi",7.0,525632,262000000,495900000,757900000
Frozen,102.0,"Adventure,Animation,Comedy",7.5,516998,400700000,875700000,1276400000
Black Panther,134.0,"Action,Adventure,Sci-Fi",7.3,516148,700100000,646900000,1347000000
Arrival,116.0,"Drama,Mystery,Sci-Fi",7.9,515483,100500000,102800000,203300000
Doctor Strange,115.0,"Action,Adventure,Fantasy",7.5,514510,232600000,445100000,677700000
Ant-Man,117.0,"Action,Adventure,Comedy",7.3,501213,180200000,339100000,519300000
Looper,113.0,"Action,Crime,Drama",7.4,500595,66500000,110000000,176500000

In [57]:
joined_df.sort_values(by=['total_gross'], ascending=False).head(60)

,runtime_minutes,genres,averagerating,numvotes,domestic_gross,foreign_gross,total_gross
Avengers: Infinity War,149.0,"Action,Adventure,Sci-Fi",8.5,670926,678800000,1369000000,2047800000
Jurassic World,124.0,"Action,Adventure,Sci-Fi",7.0,539338,652300000,1019000000,1671300000
Furious 7,137.0,"Action,Crime,Thriller",7.2,335074,353000000,1163000000,1516000000
Avengers: Age of Ultron,141.0,"Action,Adventure,Sci-Fi",7.3,665594,459000000,946400000,1405400000
Black Panther,134.0,"Action,Adventure,Sci-Fi",7.3,516148,700100000,646900000,1347000000
Star Wars: The Last Jedi,152.0,"Action,Adventure,Fantasy",7.1,462903,620200000,712400000,1332600000
Jurassic World: Fallen Kingdom,128.0,"Action,Adventure,Sci-Fi",6.2,219125,417700000,891800000,1309500000
Frozen,102.0,"Adventure,Animation,Comedy",7.5,516998,400700000,875700000,1276400000
Incredibles 2,118.0,"Action,Adventure,Animation",7.7,203510,608600000,634200000,1242800000
The Fate of the Furious,136.0,"Action,Crime,Thriller",6.7,179774,226000000,1010000000,1236000000
Iron Man 3,130.0,"Action,Adventure,Sci-Fi",7.2,692794,409000000,805800000,1214800000
Minions,91.0,"Adventure,Animation,Comedy",6.4,193917,336000000,823400000,1159400000
Captain America: Civil War,147.0,"Action,Adventure,Sci-Fi",7.8,583507,408100000,745200000,1153300000
Aquaman,143.0,"Action,Adventure,Fantasy",7.1,263328,335100000,812700000,1147800000
Transformers: Dark of the Moon,154.0,"Action,Adventure,Sci-Fi",6.2,366409,352400000,771400000,1123800000
Skyfall,143.0,"Action,Adventure,Thriller",7.8,592221,304400000,804200000,1108600000
Transformers: Age of Extinction,165.0,"Action,Adventure,Sci-Fi",5.7,283486,245400000,858600000,1104000000
The Dark Knight Rises,164.0,"Action,Thriller",8.4,1387769,448100000,636800000,1084900000
Toy Story 3,103.0,"Adventure,Animation,Comedy",8.3,682218,415000000,652000000,1067000000
Rogue One: A Star Wars Story,133.0,"Action,Adventure,Sci-Fi",7.8,478592,532200000,523900000,1056100000
Pirates of the Caribbean: On Stranger Tides,136.0,"Action,Adventure,Fantasy",6.6,447624,241100000,804600000,1045700000
Despicable Me 3,89.0,"Adventure,Animation,Comedy",6.3,92580,264600000,770200000,1034800000
Finding Dory,97.0,"Adventure,Animation,Comedy",7.3,213542,486300000,542300000,1028600000
Zootopia,108.0,"Adventure,Animation,Comedy",8.0,383446,341300000,682500000,1023800000
The Hobbit: An Unexpected Journey,169.0,"Adventure,Family,Fantasy",7.9,719629,303000000,718100000,1021100000
Despicable Me 2,98.0,"Adventure,Animation,Comedy",7.4,344230,368100000,602700000,970800000
Jumanji: Welcome to the Jungle,119.0,"Action,Adventure,Comedy",7.0,242735,404500000,557600000,962100000
The Hobbit: The Desolation of Smaug,161.0,"Adventure,Fantasy",7.8,565563,258399999,700000000,958399999
The Hobbit: The Battle of the Five Armies,144.0,"Adventure,Fantasy",7.4,438621,255100000,700900000,956000000
Bohemian Rhapsody,134.0,"Biography,Drama,Music",8.0,345466,216400000,687200000,903600000
Spectre,148.0,"Action,Adventure,Thriller",6.8,352504,200100000,680600000,880700000
Spider-Man: Homecoming,133.0,"Action,Adventure,Sci-Fi",7.5,426302,334200000,546000000,880200000
Ice Age: Continental Drift,88.0,"Adventure,Animation,Comedy",6.6,175601,161300000,715900000,877200000
The Secret Life of Pets,87.0,"Adventure,Animation,Comedy",6.5,161997,368400000,507100000,875500000
Batman v Superman: Dawn of Justice,151.0,"Action,Adventure,Fantasy",6.5,576909,330400000,543300000,873700000
The Hunger Games: Catching Fire,146.0,"Action,Adventure,Sci-Fi",7.5,575455,424700000,440300000,865000000
Guardians of the Galaxy Vol. 2,136.0,"Action,Adventure,Comedy",7.7,482917,389800000,473900000,863700000
Inside Out,95.0,"Adventure,Animation,Comedy",8.2,536181,356500000,501100000,857600000
Thor: Ragnarok,130.0,"Action,Adventure,Comedy",7.9,482995,315100000,538900000,854000000
Inception,148.0,"Action,Adventure,Sci-Fi",8.8,1841066,292600000,535700000,828300000
Wonder Woman,141.0,"Action,Adventure,Fantasy",7.5,487527,412600000,409300000,821900000
Coco,105.0,"Adventure,Animation,Comedy",8.4,277194,209700000,597400000,807100000
Pirates of the Caribbean: Dead Men Tell No Tales,129.0,"Action,Adventure,Fantasy",6.6,228592,172600000,622300000,794900000
Mission: Impossible - Fallout,147.0,"Action,Adventure,Thriller",7.8,233877,220200000,571000000,791200000
Fast & Furious 6,130.0,"Action,Crime,Thriller",7.1,346747,238700000,550000000,788700000
Deadpool,108.0,"Action,Adventure,Comedy",8.0,820847,363100000,420000000,783100000
Deadpool 2,119.0,"Action,Adventure,Comedy",7.8,391735,318500000,460500000,779000000
Guardians of the Galaxy,121.0,"Action,Adventure,Comedy",8.1,948394,333200000,440200000,773400000
Maleficent,97.0,"Action,Adventure,Family",7.0,305832,241400000,517100000,758500000
The Amazing Spider-Man,136.0,"Action,Adventure,Sci-Fi",7.0,525632,262000000,495900000,757900000
The Hunger Games: Mockingjay - Part 1,123.0,"Action,Adventure,Sci-Fi",6.6,379050,337100000,418200000,755300000
Shrek Forever After,93.0,"Adventure,Animation,Comedy",6.3,167532,238700000,513900000,752600000
X-Men: Days of Future Past,132.0,"Action,Adventure,Sci-Fi",8.0,620079,233900000,513900000,747800000
Madagascar 3: Europe's Most Wanted,93.0,"Adventure,Animation,Comedy",6.8,146858,216400000,530500000,746900000
Suicide Squad,123.0,"Action,Adventure,Fantasy",6.0,533039,325100000,421700000,746800000
Monsters University,104.0,"Adventure,Animation,Comedy",7.3,291887,268500000,475700000,744200000
Gravity,91.0,"Drama,Sci-Fi,Thriller",7.7,710018,274100000,449100000,723200000
Captain America: The Winter Soldier,136.0,"Action,Adventure,Sci-Fi",7.8,666252,259800000,454500000,714300000
Dawn of the Planet of the Apes,130.0,"Action,Adventure,Drama",7.6,390199,208500000,502100000,710600000
The Amazing Spider-Man 2,142.0,"Action,Adventure,Sci-Fi",6.6,388363,202900000,506100000,709000000

# 3 THE NUMBERS

In [58]:
##Loading up the third dataframe, THE NUMBERS, with Pandas.
numbers = pd.read_csv("zippedData/tn.movie_budgets.csv.gz")
numbers

,id,release_date,movie,production_budget,domestic_gross,worldwide_gross
0,1,"Dec 18, 2009",Avatar,"$425,000,000","$760,507,625","$2,776,345,279"
1,2,"May 20, 2011",Pirates of the Caribbean: On Stranger Tides,"$410,600,000","$241,063,875","$1,045,663,875"
2,3,"Jun 7, 2019",Dark Phoenix,"$350,000,000","$42,762,350","$149,762,350"
3,4,"May 1, 2015",Avengers: Age of Ultron,"$330,600,000","$459,005,868","$1,403,013,963"
4,5,"Dec 15, 2017",Star Wars Ep. VIII: The Last Jedi,"$317,000,000","$620,181,382","$1,316,721,747"
...,...,...,...,...,...,...
5777,78,"Dec 31, 2018",Red 11,"$7,000",$0,$0
5778,79,"Apr 2, 1999",Following,"$6,000","$48,482","$240,495"
5779,80,"Jul 13, 2005",Return to the Land of Wonders,"$5,000","$1,338","$1,338"
5780,81,"Sep 29, 2015",A Plague So Pleasant,"$1,400",$0,$0
5781,82,"Aug 5, 2005",My Date With Drew,"$1,100","$181,041","$181,041"

In [59]:
numbers = numbers.drop(['id', 'domestic_gross'], axis=1)

In [60]:
numbers.set_index('movie', inplace=True)

In [61]:
numbers.head()

,release_date,production_budget,worldwide_gross
movie,,,
Avatar,"Dec 18, 2009","$425,000,000","$2,776,345,279"
Pirates of the Caribbean: On Stranger Tides,"May 20, 2011","$410,600,000","$1,045,663,875"
Dark Phoenix,"Jun 7, 2019","$350,000,000","$149,762,350"
Avengers: Age of Ultron,"May 1, 2015","$330,600,000","$1,403,013,963"
Star Wars Ep. VIII: The Last Jedi,"Dec 15, 2017","$317,000,000","$1,316,721,747"

In [62]:
numbers.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5782 entries, Avatar to My Date With Drew
Data columns (total 3 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   release_date       5782 non-null   object
 1   production_budget  5782 non-null   object
 2   worldwide_gross    5782 non-null   object
dtypes: object(3)
memory usage: 180.7+ KB

In [63]:
numbers['release_date'] = pd.to_datetime(numbers['release_date'])

In [64]:
numbers.head(60)

,release_date,production_budget,worldwide_gross
movie,,,
Avatar,2009-12-18,"$425,000,000","$2,776,345,279"
Pirates of the Caribbean: On Stranger Tides,2011-05-20,"$410,600,000","$1,045,663,875"
Dark Phoenix,2019-06-07,"$350,000,000","$149,762,350"
Avengers: Age of Ultron,2015-05-01,"$330,600,000","$1,403,013,963"
Star Wars Ep. VIII: The Last Jedi,2017-12-15,"$317,000,000","$1,316,721,747"
Star Wars Ep. VII: The Force Awakens,2015-12-18,"$306,000,000","$2,053,311,220"
Avengers: Infinity War,2018-04-27,"$300,000,000","$2,048,134,200"
Pirates of the Caribbean: At Worldâs End,2007-05-24,"$300,000,000","$963,420,425"
Justice League,2017-11-17,"$300,000,000","$655,945,209"
Spectre,2015-11-06,"$300,000,000","$879,620,923"
The Dark Knight Rises,2012-07-20,"$275,000,000","$1,084,439,099"
Solo: A Star Wars Story,2018-05-25,"$275,000,000","$393,151,347"
The Lone Ranger,2013-07-02,"$275,000,000","$260,002,115"
John Carter,2012-03-09,"$275,000,000","$282,778,100"
Tangled,2010-11-24,"$260,000,000","$586,477,240"
Spider-Man 3,2007-05-04,"$258,000,000","$894,860,230"
Captain America: Civil War,2016-05-06,"$250,000,000","$1,140,069,413"
Batman v Superman: Dawn of Justice,2016-03-25,"$250,000,000","$867,500,281"
The Hobbit: An Unexpected Journey,2012-12-14,"$250,000,000","$1,017,003,568"
Harry Potter and the Half-Blood Prince,2009-07-15,"$250,000,000","$935,213,767"
The Hobbit: The Desolation of Smaug,2013-12-13,"$250,000,000","$960,366,855"
The Hobbit: The Battle of the Five Armies,2014-12-17,"$250,000,000","$945,577,621"
The Fate of the Furious,2017-04-14,"$250,000,000","$1,234,846,267"
Superman Returns,2006-06-28,"$232,000,000","$374,085,065"
Pirates of the Caribbean: Dead Men Tell No Tales,2017-05-26,"$230,000,000","$788,241,137"
Quantum of Solace,2008-11-14,"$230,000,000","$591,692,078"
The Avengers,2012-05-04,"$225,000,000","$1,517,935,897"
Pirates of the Caribbean: Dead Manâs Chest,2006-07-07,"$225,000,000","$1,066,215,812"
Man of Steel,2013-06-14,"$225,000,000","$667,999,518"
The Chronicles of Narnia: Prince Caspian,2008-05-16,"$225,000,000","$417,341,288"
The Amazing Spider-Man,2012-07-03,"$220,000,000","$757,890,267"
Battleship,2012-05-18,"$220,000,000","$313,477,717"
Transformers: The Last Knight,2017-06-21,"$217,000,000","$602,893,340"
Jurassic World,2015-06-12,"$215,000,000","$1,648,854,864"
Men in Black 3,2012-05-25,"$215,000,000","$654,213,485"
Transformers: Revenge of the Fallen,2009-06-24,"$210,000,000","$836,519,699"
Transformers: Age of Extinction,2014-06-27,"$210,000,000","$1,104,039,076"
X-Men: The Last Stand,2006-05-26,"$210,000,000","$459,260,946"
Robin Hood,2010-05-14,"$210,000,000","$322,459,006"
King Kong,2005-12-14,"$207,000,000","$550,517,357"
The Golden Compass,2007-12-07,"$205,000,000","$367,262,558"
Black Panther,2018-02-16,"$200,000,000","$1,348,258,224"
Titanic,1997-12-19,"$200,000,000","$2,208,208,395"
Incredibles 2,2018-06-15,"$200,000,000","$1,242,520,711"
Rogue One: A Star Wars Story,2016-12-16,"$200,000,000","$1,049,102,856"
Finding Dory,2016-06-17,"$200,000,000","$1,021,215,193"
Toy Story 3,2010-06-18,"$200,000,000","$1,068,879,522"
Iron Man 3,2013-05-03,"$200,000,000","$1,215,392,272"
Guardians of the Galaxy Vol 2,2017-05-05,"$200,000,000","$862,316,233"
Spider-Man 2,2004-06-30,"$200,000,000","$795,110,670"
Alice in Wonderland,2010-03-05,"$200,000,000","$1,025,491,110"
Skyfall,2012-11-08,"$200,000,000","$1,110,526,981"
Monsters University,2013-06-21,"$200,000,000","$743,588,329"
Oz the Great and Powerful,2013-03-08,"$200,000,000","$490,359,051"
X-Men: Days of Future Past,2014-05-23,"$200,000,000","$747,862,775"
The Amazing Spider-Man 2,2014-05-02,"$200,000,000","$708,996,336"
Cars 2,2011-06-24,"$200,000,000","$560,155,383"
Tron: Legacy,2010-12-17,"$200,000,000","$400,062,763"
2012,2009-11-13,"$200,000,000","$757,677,748"
Fantastic Beasts: The Crimes of Grindelwald,2018-11-16,"$200,000,000","$652,220,086"

In [65]:
numbers['production_budget']= numbers['production_budget'].apply(lambda x: x.replace(',', '').replace('$','')).astype(float)

In [66]:
numbers['production_budget']

movie
Avatar                                         425000000.0
Pirates of the Caribbean: On Stranger Tides    410600000.0
Dark Phoenix                                   350000000.0
Avengers: Age of Ultron                        330600000.0
Star Wars Ep. VIII: The Last Jedi              317000000.0
                                                  ...
Red 11                                              7000.0
Following                                           6000.0
Return to the Land of Wonders                       5000.0
A Plague So Pleasant                                1400.0
My Date With Drew                                   1100.0
Name: production_budget, Length: 5782, dtype: float64

In [67]:
numbers['worldwide_gross']= numbers['worldwide_gross'].apply(lambda x: x.replace(',', '').replace('$','')).astype(float)

In [68]:
numbers['worldwide_gross']

movie
Avatar                                         2.776345e+09
Pirates of the Caribbean: On Stranger Tides    1.045664e+09
Dark Phoenix                                   1.497624e+08
Avengers: Age of Ultron                        1.403014e+09
Star Wars Ep. VIII: The Last Jedi              1.316722e+09
                                                   ...
Red 11                                         0.000000e+00
Following                                      2.404950e+05
Return to the Land of Wonders                  1.338000e+03
A Plague So Pleasant                           0.000000e+00
My Date With Drew                              1.810410e+05
Name: worldwide_gross, Length: 5782, dtype: float64

In [69]:
numbers.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5782 entries, Avatar to My Date With Drew
Data columns (total 3 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   release_date       5782 non-null   datetime64[ns]
 1   production_budget  5782 non-null   float64
 2   worldwide_gross    5782 non-null   float64
dtypes: datetime64[ns](1), float64(2)
memory usage: 340.7+ KB

In [70]:
numbers['roi'] = numbers['worldwide_gross'] - numbers['production_budget']

In [71]:
numbers.head(60)

,release_date,production_budget,worldwide_gross,roi
movie,,,,
Avatar,2009-12-18,425000000.0,2.776345e+09,2.351345e+09
Pirates of the Caribbean: On Stranger Tides,2011-05-20,410600000.0,1.045664e+09,6.350639e+08
Dark Phoenix,2019-06-07,350000000.0,1.497624e+08,-2.002376e+08
Avengers: Age of Ultron,2015-05-01,330600000.0,1.403014e+09,1.072414e+09
Star Wars Ep. VIII: The Last Jedi,2017-12-15,317000000.0,1.316722e+09,9.997217e+08
Star Wars Ep. VII: The Force Awakens,2015-12-18,306000000.0,2.053311e+09,1.747311e+09
Avengers: Infinity War,2018-04-27,300000000.0,2.048134e+09,1.748134e+09
Pirates of the Caribbean: At Worldâs End,2007-05-24,300000000.0,9.634204e+08,6.634204e+08
Justice League,2017-11-17,300000000.0,6.559452e+08,3.559452e+08
Spectre,2015-11-06,300000000.0,8.796209e+08,5.796209e+08
The Dark Knight Rises,2012-07-20,275000000.0,1.084439e+09,8.094391e+08
Solo: A Star Wars Story,2018-05-25,275000000.0,3.931513e+08,1.181513e+08
The Lone Ranger,2013-07-02,275000000.0,2.600021e+08,-1.499788e+07
John Carter,2012-03-09,275000000.0,2.827781e+08,7.778100e+06
Tangled,2010-11-24,260000000.0,5.864772e+08,3.264772e+08
Spider-Man 3,2007-05-04,258000000.0,8.948602e+08,6.368602e+08
Captain America: Civil War,2016-05-06,250000000.0,1.140069e+09,8.900694e+08
Batman v Superman: Dawn of Justice,2016-03-25,250000000.0,8.675003e+08,6.175003e+08
The Hobbit: An Unexpected Journey,2012-12-14,250000000.0,1.017004e+09,7.670036e+08
Harry Potter and the Half-Blood Prince,2009-07-15,250000000.0,9.352138e+08,6.852138e+08
The Hobbit: The Desolation of Smaug,2013-12-13,250000000.0,9.603669e+08,7.103669e+08
The Hobbit: The Battle of the Five Armies,2014-12-17,250000000.0,9.455776e+08,6.955776e+08
The Fate of the Furious,2017-04-14,250000000.0,1.234846e+09,9.848463e+08
Superman Returns,2006-06-28,232000000.0,3.740851e+08,1.420851e+08
Pirates of the Caribbean: Dead Men Tell No Tales,2017-05-26,230000000.0,7.882411e+08,5.582411e+08
Quantum of Solace,2008-11-14,230000000.0,5.916921e+08,3.616921e+08
The Avengers,2012-05-04,225000000.0,1.517936e+09,1.292936e+09
Pirates of the Caribbean: Dead Manâs Chest,2006-07-07,225000000.0,1.066216e+09,8.412158e+08
Man of Steel,2013-06-14,225000000.0,6.679995e+08,4.429995e+08
The Chronicles of Narnia: Prince Caspian,2008-05-16,225000000.0,4.173413e+08,1.923413e+08
The Amazing Spider-Man,2012-07-03,220000000.0,7.578903e+08,5.378903e+08
Battleship,2012-05-18,220000000.0,3.134777e+08,9.347772e+07
Transformers: The Last Knight,2017-06-21,217000000.0,6.028933e+08,3.858933e+08
Jurassic World,2015-06-12,215000000.0,1.648855e+09,1.433855e+09
Men in Black 3,2012-05-25,215000000.0,6.542135e+08,4.392135e+08
Transformers: Revenge of the Fallen,2009-06-24,210000000.0,8.365197e+08,6.265197e+08
Transformers: Age of Extinction,2014-06-27,210000000.0,1.104039e+09,8.940391e+08
X-Men: The Last Stand,2006-05-26,210000000.0,4.592609e+08,2.492609e+08
Robin Hood,2010-05-14,210000000.0,3.224590e+08,1.124590e+08
King Kong,2005-12-14,207000000.0,5.505174e+08,3.435174e+08
The Golden Compass,2007-12-07,205000000.0,3.672626e+08,1.622626e+08
Black Panther,2018-02-16,200000000.0,1.348258e+09,1.148258e+09
Titanic,1997-12-19,200000000.0,2.208208e+09,2.008208e+09
Incredibles 2,2018-06-15,200000000.0,1.242521e+09,1.042521e+09
Rogue One: A Star Wars Story,2016-12-16,200000000.0,1.049103e+09,8.491029e+08
Finding Dory,2016-06-17,200000000.0,1.021215e+09,8.212152e+08
Toy Story 3,2010-06-18,200000000.0,1.068880e+09,8.688795e+08
Iron Man 3,2013-05-03,200000000.0,1.215392e+09,1.015392e+09
Guardians of the Galaxy Vol 2,2017-05-05,200000000.0,8.623162e+08,6.623162e+08
Spider-Man 2,2004-06-30,200000000.0,7.951107e+08,5.951107e+08
Alice in Wonderland,2010-03-05,200000000.0,1.025491e+09,8.254911e+08
Skyfall,2012-11-08,200000000.0,1.110527e+09,9.105270e+08
Monsters University,2013-06-21,200000000.0,7.435883e+08,5.435883e+08
Oz the Great and Powerful,2013-03-08,200000000.0,4.903591e+08,2.903591e+08
X-Men: Days of Future Past,2014-05-23,200000000.0,7.478628e+08,5.478628e+08
The Amazing Spider-Man 2,2014-05-02,200000000.0,7.089963e+08,5.089963e+08
Cars 2,2011-06-24,200000000.0,5.601554e+08,3.601554e+08
Tron: Legacy,2010-12-17,200000000.0,4.000628e+08,2.000628e+08
2012,2009-11-13,200000000.0,7.576777e+08,5.576777e+08
Fantastic Beasts: The Crimes of Grindelwald,2018-11-16,200000000.0,6.522201e+08,4.522201e+08

In [72]:
numbers.sort_values(by=['roi'], ascending=False).head(60)

,release_date,production_budget,worldwide_gross,roi
movie,,,,
Avatar,2009-12-18,425000000.0,2.776345e+09,2.351345e+09
Titanic,1997-12-19,200000000.0,2.208208e+09,2.008208e+09
Avengers: Infinity War,2018-04-27,300000000.0,2.048134e+09,1.748134e+09
Star Wars Ep. VII: The Force Awakens,2015-12-18,306000000.0,2.053311e+09,1.747311e+09
Jurassic World,2015-06-12,215000000.0,1.648855e+09,1.433855e+09
Furious 7,2015-04-03,190000000.0,1.518723e+09,1.328723e+09
The Avengers,2012-05-04,225000000.0,1.517936e+09,1.292936e+09
Harry Potter and the Deathly Hallows: Part II,2011-07-15,125000000.0,1.341693e+09,1.216693e+09
Black Panther,2018-02-16,200000000.0,1.348258e+09,1.148258e+09
Jurassic World: Fallen Kingdom,2018-06-22,170000000.0,1.305773e+09,1.135773e+09
Frozen,2013-11-22,150000000.0,1.272470e+09,1.122470e+09
Beauty and the Beast,2017-03-17,160000000.0,1.259200e+09,1.099200e+09
Minions,2015-07-10,74000000.0,1.160336e+09,1.086336e+09
Avengers: Age of Ultron,2015-05-01,330600000.0,1.403014e+09,1.072414e+09
The Lord of the Rings: The Return of the King,2003-12-17,94000000.0,1.141403e+09,1.047403e+09
Incredibles 2,2018-06-15,200000000.0,1.242521e+09,1.042521e+09
Iron Man 3,2013-05-03,200000000.0,1.215392e+09,1.015392e+09
Star Wars Ep. VIII: The Last Jedi,2017-12-15,317000000.0,1.316722e+09,9.997217e+08
Aquaman,2018-12-21,160000000.0,1.146895e+09,9.868946e+08
The Fate of the Furious,2017-04-14,250000000.0,1.234846e+09,9.848463e+08
Jurassic Park,1993-06-11,63000000.0,1.038813e+09,9.758126e+08
Despicable Me 3,2017-06-30,75000000.0,1.034728e+09,9.597278e+08
Captain Marvel,2019-03-08,175000000.0,1.123062e+09,9.480616e+08
Transformers: Dark of the Moon,2011-06-29,195000000.0,1.123791e+09,9.287905e+08
Star Wars Ep. I: The Phantom Menace,1999-05-19,115000000.0,1.027045e+09,9.120447e+08
Skyfall,2012-11-08,200000000.0,1.110527e+09,9.105270e+08
The Lion King,1994-06-15,79300000.0,9.862149e+08,9.069149e+08
Despicable Me 2,2013-07-03,76000000.0,9.752168e+08,8.992168e+08
Transformers: Age of Extinction,2014-06-27,210000000.0,1.104039e+09,8.940391e+08
Captain America: Civil War,2016-05-06,250000000.0,1.140069e+09,8.900694e+08
Jumanji: Welcome to the Jungle,2017-12-20,90000000.0,9.644962e+08,8.744962e+08
Zootopia,2016-03-04,150000000.0,1.019430e+09,8.694296e+08
Toy Story 3,2010-06-18,200000000.0,1.068880e+09,8.688795e+08
Shrek 2,2004-05-19,70000000.0,9.370081e+08,8.670081e+08
Harry Potter and the Sorcererâs Stone,2001-11-16,125000000.0,9.750476e+08,8.500476e+08
Rogue One: A Star Wars Story,2016-12-16,200000000.0,1.049103e+09,8.491029e+08
Finding Nemo,2003-05-30,94000000.0,9.364294e+08,8.424294e+08
Pirates of the Caribbean: Dead Manâs Chest,2006-07-07,225000000.0,1.066216e+09,8.412158e+08
The Lord of the Rings: The Two Towers,2002-12-18,94000000.0,9.346996e+08,8.406996e+08
Bohemian Rhapsody,2018-11-02,55000000.0,8.949853e+08,8.399853e+08
Harry Potter and the Deathly Hallows: Part I,2010-11-19,125000000.0,9.604316e+08,8.354316e+08
Alice in Wonderland,2010-03-05,200000000.0,1.025491e+09,8.254911e+08
Finding Dory,2016-06-17,200000000.0,1.021215e+09,8.212152e+08
The Dark Knight,2008-07-18,185000000.0,1.001996e+09,8.169962e+08
The Secret Life of Pets,2016-07-08,75000000.0,8.867505e+08,8.117505e+08
The Dark Knight Rises,2012-07-20,275000000.0,1.084439e+09,8.094391e+08
Harry Potter and the Order of the Phoenix,2007-07-11,150000000.0,9.430765e+08,7.930765e+08
The Jungle Book,2016-04-15,175000000.0,9.628545e+08,7.878545e+08
Ice Age: Continental Drift,2012-07-13,95000000.0,8.797651e+08,7.847651e+08
ET: The Extra-Terrestrial,1982-06-11,10500000.0,7.929653e+08,7.824653e+08
Harry Potter and the Chamber of Secrets,2002-11-15,100000000.0,8.792251e+08,7.792251e+08
The Lord of the Rings: The Fellowship of the Ring,2001-12-19,109000000.0,8.872110e+08,7.782110e+08
Star Wars Ep. IV: A New Hope,1977-05-25,11000000.0,7.865980e+08,7.755980e+08
Ice Age: Dawn of the Dinosaurs,2009-07-01,90000000.0,8.597019e+08,7.697019e+08
The Hobbit: An Unexpected Journey,2012-12-14,250000000.0,1.017004e+09,7.670036e+08
Harry Potter and the Goblet of Fire,2005-11-18,150000000.0,8.970998e+08,7.470998e+08
Deadpool,2016-02-12,58000000.0,8.010256e+08,7.430256e+08
Independence Day,1996-07-02,75000000.0,8.174009e+08,7.424009e+08
Venom,2018-10-05,116000000.0,8.536286e+08,7.376286e+08
The Hunger Games: Catching Fire,2013-11-22,130000000.0,8.648680e+08,7.348680e+08

In [73]:
numbers

,release_date,production_budget,worldwide_gross,roi
movie,,,,
Avatar,2009-12-18,425000000.0,2.776345e+09,2.351345e+09
Pirates of the Caribbean: On Stranger Tides,2011-05-20,410600000.0,1.045664e+09,6.350639e+08
Dark Phoenix,2019-06-07,350000000.0,1.497624e+08,-2.002376e+08
Avengers: Age of Ultron,2015-05-01,330600000.0,1.403014e+09,1.072414e+09
Star Wars Ep. VIII: The Last Jedi,2017-12-15,317000000.0,1.316722e+09,9.997217e+08
...,...,...,...,...
Red 11,2018-12-31,7000.0,0.000000e+00,-7.000000e+03
Following,1999-04-02,6000.0,2.404950e+05,2.344950e+05
Return to the Land of Wonders,2005-07-13,5000.0,1.338000e+03,-3.662000e+03
A Plague So Pleasant,2015-09-29,1400.0,0.000000e+00,-1.400000e+03
My Date With Drew,2005-08-05,1100.0,1.810410e+05,1.799410e+05

In [74]:
joined_df

,runtime_minutes,genres,averagerating,numvotes,domestic_gross,foreign_gross,total_gross
Inception,148.0,"Action,Adventure,Sci-Fi",8.8,1841066,292600000,535700000,828300000
The Dark Knight Rises,164.0,"Action,Thriller",8.4,1387769,448100000,636800000,1084900000
Interstellar,169.0,"Adventure,Drama,Sci-Fi",8.6,1299334,188000000,489400000,677400000
Django Unchained,165.0,"Drama,Western",8.4,1211405,162800000,262600000,425400000
The Wolf of Wall Street,180.0,"Biography,Crime,Drama",8.2,1035358,116900000,275100000,392000000
...,...,...,...,...,...,...,...
What to Expect When You're Expecting,110.0,"Comedy,Drama,Romance",5.7,65890,41200000,43200000,84400000
Dark Skies,97.0,"Horror,Sci-Fi,Thriller",6.3,65754,17400000,9000000,26400000
Baahubali 2: The Conclusion,167.0,"Action,Drama",8.3,65656,20200000,234000000,254200000
The Sitter,81.0,Comedy,5.7,65575,30400000,4500000,34900000
Inside Job,109.0,"Crime,Documentary",8.3,65304,4300000,3600000,7900000

In [75]:
triple_df = joined_df.join(numbers, how='inner')

triple_df

,runtime_minutes,genres,averagerating,numvotes,domestic_gross,foreign_gross,total_gross,release_date,production_budget,worldwide_gross,roi
10 Cloverfield Lane,103.0,"Drama,Horror,Mystery",7.2,260383,72100000,38100000,110200000,2016-03-11,5000000.0,1.082864e+08,103286422.0
12 Years a Slave,134.0,"Biography,Drama,History",8.1,577301,56700000,131100000,187800000,2013-10-18,20000000.0,1.810253e+08,161025343.0
127 Hours,94.0,"Adventure,Biography,Drama",7.6,323949,18300000,42400000,60700000,2010-11-05,18000000.0,6.021717e+07,42217171.0
2 Guns,109.0,"Action,Comedy,Crime",6.7,182025,75600000,56300000,131900000,2013-08-02,61000000.0,1.324930e+08,71493015.0
21 Jump Street,109.0,"Action,Comedy,Crime",7.2,477771,138400000,63100000,201500000,2012-03-16,42000000.0,2.028124e+08,160812429.0
...,...,...,...,...,...,...,...,...,...,...,...
X-Men: First Class,131.0,"Action,Adventure,Sci-Fi",7.7,608930,146400000,207200000,353600000,2011-06-03,160000000.0,3.554083e+08,195408305.0
Young Adult,94.0,"Comedy,Drama",6.3,74071,16300000,6600000,22900000,2011-12-09,12000000.0,2.275036e+07,10750356.0
Your Highness,102.0,"Adventure,Comedy,Fantasy",5.5,92940,21600000,3300000,24900000,2011-04-08,50000000.0,2.612164e+07,-23878362.0
Zero Dark Thirty,157.0,"Drama,Thriller",7.4,251072,95700000,37100000,132800000,2012-12-19,52500000.0,1.346124e+08,82112435.0
Zootopia,108.0,"Adventure,Animation,Comedy",8.0,383446,341300000,682500000,1023800000,2016-03-04,150000000.0,1.019430e+09,869429616.0

In [76]:
triple_df.sort_values(by=['total_gross'], ascending=False).head(60)

,runtime_minutes,genres,averagerating,numvotes,domestic_gross,foreign_gross,total_gross,release_date,production_budget,worldwide_gross,roi
Avengers: Infinity War,149.0,"Action,Adventure,Sci-Fi",8.5,670926,678800000,1369000000,2047800000,2018-04-27,300000000.0,2.048134e+09,1.748134e+09
Jurassic World,124.0,"Action,Adventure,Sci-Fi",7.0,539338,652300000,1019000000,1671300000,2015-06-12,215000000.0,1.648855e+09,1.433855e+09
Furious 7,137.0,"Action,Crime,Thriller",7.2,335074,353000000,1163000000,1516000000,2015-04-03,190000000.0,1.518723e+09,1.328723e+09
Avengers: Age of Ultron,141.0,"Action,Adventure,Sci-Fi",7.3,665594,459000000,946400000,1405400000,2015-05-01,330600000.0,1.403014e+09,1.072414e+09
Black Panther,134.0,"Action,Adventure,Sci-Fi",7.3,516148,700100000,646900000,1347000000,2018-02-16,200000000.0,1.348258e+09,1.148258e+09
Jurassic World: Fallen Kingdom,128.0,"Action,Adventure,Sci-Fi",6.2,219125,417700000,891800000,1309500000,2018-06-22,170000000.0,1.305773e+09,1.135773e+09
Frozen,102.0,"Adventure,Animation,Comedy",7.5,516998,400700000,875700000,1276400000,2013-11-22,150000000.0,1.272470e+09,1.122470e+09
Incredibles 2,118.0,"Action,Adventure,Animation",7.7,203510,608600000,634200000,1242800000,2018-06-15,200000000.0,1.242521e+09,1.042521e+09
The Fate of the Furious,136.0,"Action,Crime,Thriller",6.7,179774,226000000,1010000000,1236000000,2017-04-14,250000000.0,1.234846e+09,9.848463e+08
Iron Man 3,130.0,"Action,Adventure,Sci-Fi",7.2,692794,409000000,805800000,1214800000,2013-05-03,200000000.0,1.215392e+09,1.015392e+09
Minions,91.0,"Adventure,Animation,Comedy",6.4,193917,336000000,823400000,1159400000,2015-07-10,74000000.0,1.160336e+09,1.086336e+09
Captain America: Civil War,147.0,"Action,Adventure,Sci-Fi",7.8,583507,408100000,745200000,1153300000,2016-05-06,250000000.0,1.140069e+09,8.900694e+08
Aquaman,143.0,"Action,Adventure,Fantasy",7.1,263328,335100000,812700000,1147800000,2018-12-21,160000000.0,1.146895e+09,9.868946e+08
Transformers: Dark of the Moon,154.0,"Action,Adventure,Sci-Fi",6.2,366409,352400000,771400000,1123800000,2011-06-29,195000000.0,1.123791e+09,9.287905e+08
Skyfall,143.0,"Action,Adventure,Thriller",7.8,592221,304400000,804200000,1108600000,2012-11-08,200000000.0,1.110527e+09,9.105270e+08
Transformers: Age of Extinction,165.0,"Action,Adventure,Sci-Fi",5.7,283486,245400000,858600000,1104000000,2014-06-27,210000000.0,1.104039e+09,8.940391e+08
The Dark Knight Rises,164.0,"Action,Thriller",8.4,1387769,448100000,636800000,1084900000,2012-07-20,275000000.0,1.084439e+09,8.094391e+08
Toy Story 3,103.0,"Adventure,Animation,Comedy",8.3,682218,415000000,652000000,1067000000,2010-06-18,200000000.0,1.068880e+09,8.688795e+08
Rogue One: A Star Wars Story,133.0,"Action,Adventure,Sci-Fi",7.8,478592,532200000,523900000,1056100000,2016-12-16,200000000.0,1.049103e+09,8.491029e+08
Pirates of the Caribbean: On Stranger Tides,136.0,"Action,Adventure,Fantasy",6.6,447624,241100000,804600000,1045700000,2011-05-20,410600000.0,1.045664e+09,6.350639e+08
Despicable Me 3,89.0,"Adventure,Animation,Comedy",6.3,92580,264600000,770200000,1034800000,2017-06-30,75000000.0,1.034728e+09,9.597278e+08
Finding Dory,97.0,"Adventure,Animation,Comedy",7.3,213542,486300000,542300000,1028600000,2016-06-17,200000000.0,1.021215e+09,8.212152e+08
Zootopia,108.0,"Adventure,Animation,Comedy",8.0,383446,341300000,682500000,1023800000,2016-03-04,150000000.0,1.019430e+09,8.694296e+08
The Hobbit: An Unexpected Journey,169.0,"Adventure,Family,Fantasy",7.9,719629,303000000,718100000,1021100000,2012-12-14,250000000.0,1.017004e+09,7.670036e+08
Despicable Me 2,98.0,"Adventure,Animation,Comedy",7.4,344230,368100000,602700000,970800000,2013-07-03,76000000.0,9.752168e+08,8.992168e+08
Jumanji: Welcome to the Jungle,119.0,"Action,Adventure,Comedy",7.0,242735,404500000,557600000,962100000,2017-12-20,90000000.0,9.644962e+08,8.744962e+08
The Hobbit: The Desolation of Smaug,161.0,"Adventure,Fantasy",7.8,565563,258399999,700000000,958399999,2013-12-13,250000000.0,9.603669e+08,7.103669e+08
The Hobbit: The Battle of the Five Armies,144.0,"Adventure,Fantasy",7.4,438621,255100000,700900000,956000000,2014-12-17,250000000.0,9.455776e+08,6.955776e+08
Bohemian Rhapsody,134.0,"Biography,Drama,Music",8.0,345466,216400000,687200000,903600000,2018-11-02,55000000.0,8.949853e+08,8.399853e+08
Spectre,148.0,"Action,Adventure,Thriller",6.8,352504,200100000,680600000,880700000,2015-11-06,300000000.0,8.796209e+08,5.796209e+08
Spider-Man: Homecoming,133.0,"Action,Adventure,Sci-Fi",7.5,426302,334200000,546000000,880200000,2017-07-07,175000000.0,8.801664e+08,7.051664e+08
Ice Age: Continental Drift,88.0,"Adventure,Animation,Comedy",6.6,175601,161300000,715900000,877200000,2012-07-13,95000000.0,8.797651e+08,7.847651e+08
The Secret Life of Pets,87.0,"Adventure,Animation,Comedy",6.5,161997,368400000,507100000,875500000,2016-07-08,75000000.0,8.867505e+08,8.117505e+08
Batman v Superman: Dawn of Justice,151.0,"Action,Adventure,Fantasy",6.5,576909,330400000,543300000,873700000,2016-03-25,250000000.0,8.675003e+08,6.175003e+08
The Hunger Games: Catching Fire,146.0,"Action,Adventure,Sci-Fi",7.5,575455,424700000,440300000,865000000,2013-11-22,130000000.0,8.648680e+08,7.348680e+08
Inside Out,95.0,"Adventure,Animation,Comedy",8.2,536181,356500000,501100000,857600000,2015-06-19,175000000.0,8.542360e+08,6.792360e+08
Thor: Ragnarok,130.0,"Action,Adventure,Comedy",7.9,482995,315100000,538900000,854000000,2017-11-03,180000000.0,8.469800e+08,6.669800e+08
Inception,148.0,"Action,Adventure,Sci-Fi",8.8,1841066,292600000,535700000,828300000,2010-07-16,160000000.0,8.355246e+08,6.755246e+08
Wonder Woman,141.0,"Action,Adventure,Fantasy",7.5,487527,412600000,409300000,821900000,2017-06-02,150000000.0,8.211334e+08,6.711334e+08
Coco,105.0,"Adventure,Animation,Comedy",8.4,277194,209700000,597400000,807100000,2017-11-22,175000000.0,7.980081e+08,6.230081e+08
Pirates of the Caribbean: Dead Men Tell No Tales,129.0,"Action,Adventure,Fantasy",6.6,228592,172600000,622300000,794900000,2017-05-26,230000000.0,7.882411e+08,5.582411e+08
Deadpool,108.0,"Action,Adventure,Comedy",8.0,820847,363100000,420000000,783100000,2016-02-12,58000000.0,8.010256e+08,7.430256e+08
Deadpool 2,119.0,"Action,Adventure,Comedy",7.8,391735,318500000,460500000,779000000,2018-05-18,110000000.0,7.866806e+08,6.766806e+08
Guardians of the Galaxy,121.0,"Action,Adventure,Comedy",8.1,948394,333200000,440200000,773400000,2014-08-01,170000000.0,7.708675e+08,6.008675e+08
Maleficent,97.0,"Action,Adventure,Family",7.0,305832,241400000,517100000,758500000,2014-05-30,180000000.0,7.585367e+08,5.785367e+08
The Amazing Spider-Man,136.0,"Action,Adventure,Sci-Fi",7.0,525632,262000000,495900000,757900000,2012-07-03,220000000.0,7.578903e+08,5.378903e+08
The Hunger Games: Mockingjay - Part 1,123.0,"Action,Adventure,Sci-Fi",6.6,379050,337100000,418200000,755300000,2014-11-21,125000000.0,7.665751e+08,6.415751e+08
Shrek Forever After,93.0,"Adventure,Animation,Comedy",6.3,167532,238700000,513900000,752600000,2010-05-21,165000000.0,7.562447e+08,5.912447e+08
X-Men: Days of Future Past,132.0,"Action,Adventure,Sci-Fi",8.0,620079,233900000,513900000,747800000,2014-05-23,200000000.0,7.478628e+08,5.478628e+08
Madagascar 3: Europe's Most Wanted,93.0,"Adventure,Animation,Comedy",6.8,146858,216400000,530500000,746900000,2012-06-08,145000000.0,7.469213e+08,6.019213e+08
Suicide Squad,123.0,"Action,Adventure,Fantasy",6.0,533039,325100000,421700000,746800000,2016-08-05,175000000.0,7.460599e+08,5.710599e+08
Monsters University,104.0,"Adventure,Animation,Comedy",7.3,291887,268500000,475700000,744200000,2013-06-21,200000000.0,7.435883e+08,5.435883e+08
Gravity,91.0,"Drama,Sci-Fi,Thriller",7.7,710018,274100000,449100000,723200000,2013-10-04,110000000.0,6.936987e+08,5.836987e+08
Captain America: The Winter Soldier,136.0,"Action,Adventure,Sci-Fi",7.8,666252,259800000,454500000,714300000,2014-04-04,170000000.0,7.144019e+08,5.444019e+08
Dawn of the Planet of the Apes,130.0,"Action,Adventure,Drama",7.6,390199,208500000,502100000,710600000,2014-07-11,170000000.0,7.106446e+08,5.406446e+08
The Amazing Spider-Man 2,142.0,"Action,Adventure,Sci-Fi",6.6,388363,202900000,506100000,709000000,2014-05-02,200000000.0,7.089963e+08,5.089963e+08
It,135.0,"Horror,Thriller",7.4,359123,327500000,372900000,700400000,2017-09-08,35000000.0,6.974580e+08,6.624580e+08
The Twilight Saga: Eclipse,124.0,"Adventure,Drama,Fantasy",5.0,211733,300500000,398000000,698500000,2010-06-30,68000000.0,7.061028e+08,6.381028e+08
The Hunger Games,142.0,"Action,Adventure,Sci-Fi",7.2,795227,408000000,286400000,694400000,2012-03-23,80000000.0,6.779234e+08,5.979234e+08
Doctor Strange,115.0,"Action,Adventure,Fantasy",7.5,514510,232600000,445100000,677700000,2016-11-04,165000000.0,6.764046e+08,5.114046e+08

In [77]:
triple_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 649 entries, 10 Cloverfield Lane to Zootopia
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   runtime_minutes    649 non-null    float64
 1   genres             649 non-null    object
 2   averagerating      649 non-null    float64
 3   numvotes           649 non-null    int64
 4   domestic_gross     649 non-null    int32
 5   foreign_gross      649 non-null    int32
 6   total_gross        649 non-null    int32
 7   release_date       649 non-null    datetime64[ns]
 8   production_budget  649 non-null    float64
 9   worldwide_gross    649 non-null    float64
 10  roi                649 non-null    float64
dtypes: datetime64[ns](1), float64(5), int32(3), int64(1), object(1)
memory usage: 53.2+ KB

In [78]:
triple_df.sort_values(by=['roi'], ascending=False).head(60)

,runtime_minutes,genres,averagerating,numvotes,domestic_gross,foreign_gross,total_gross,release_date,production_budget,worldwide_gross,roi
Avengers: Infinity War,149.0,"Action,Adventure,Sci-Fi",8.5,670926,678800000,1369000000,2047800000,2018-04-27,300000000.0,2.048134e+09,1.748134e+09
Jurassic World,124.0,"Action,Adventure,Sci-Fi",7.0,539338,652300000,1019000000,1671300000,2015-06-12,215000000.0,1.648855e+09,1.433855e+09
Furious 7,137.0,"Action,Crime,Thriller",7.2,335074,353000000,1163000000,1516000000,2015-04-03,190000000.0,1.518723e+09,1.328723e+09
Black Panther,134.0,"Action,Adventure,Sci-Fi",7.3,516148,700100000,646900000,1347000000,2018-02-16,200000000.0,1.348258e+09,1.148258e+09
Jurassic World: Fallen Kingdom,128.0,"Action,Adventure,Sci-Fi",6.2,219125,417700000,891800000,1309500000,2018-06-22,170000000.0,1.305773e+09,1.135773e+09
Frozen,102.0,"Adventure,Animation,Comedy",7.5,516998,400700000,875700000,1276400000,2013-11-22,150000000.0,1.272470e+09,1.122470e+09
Minions,91.0,"Adventure,Animation,Comedy",6.4,193917,336000000,823400000,1159400000,2015-07-10,74000000.0,1.160336e+09,1.086336e+09
Avengers: Age of Ultron,141.0,"Action,Adventure,Sci-Fi",7.3,665594,459000000,946400000,1405400000,2015-05-01,330600000.0,1.403014e+09,1.072414e+09
Incredibles 2,118.0,"Action,Adventure,Animation",7.7,203510,608600000,634200000,1242800000,2018-06-15,200000000.0,1.242521e+09,1.042521e+09
Iron Man 3,130.0,"Action,Adventure,Sci-Fi",7.2,692794,409000000,805800000,1214800000,2013-05-03,200000000.0,1.215392e+09,1.015392e+09
Aquaman,143.0,"Action,Adventure,Fantasy",7.1,263328,335100000,812700000,1147800000,2018-12-21,160000000.0,1.146895e+09,9.868946e+08
The Fate of the Furious,136.0,"Action,Crime,Thriller",6.7,179774,226000000,1010000000,1236000000,2017-04-14,250000000.0,1.234846e+09,9.848463e+08
Despicable Me 3,89.0,"Adventure,Animation,Comedy",6.3,92580,264600000,770200000,1034800000,2017-06-30,75000000.0,1.034728e+09,9.597278e+08
Transformers: Dark of the Moon,154.0,"Action,Adventure,Sci-Fi",6.2,366409,352400000,771400000,1123800000,2011-06-29,195000000.0,1.123791e+09,9.287905e+08
Skyfall,143.0,"Action,Adventure,Thriller",7.8,592221,304400000,804200000,1108600000,2012-11-08,200000000.0,1.110527e+09,9.105270e+08
Despicable Me 2,98.0,"Adventure,Animation,Comedy",7.4,344230,368100000,602700000,970800000,2013-07-03,76000000.0,9.752168e+08,8.992168e+08
Transformers: Age of Extinction,165.0,"Action,Adventure,Sci-Fi",5.7,283486,245400000,858600000,1104000000,2014-06-27,210000000.0,1.104039e+09,8.940391e+08
Captain America: Civil War,147.0,"Action,Adventure,Sci-Fi",7.8,583507,408100000,745200000,1153300000,2016-05-06,250000000.0,1.140069e+09,8.900694e+08
Jumanji: Welcome to the Jungle,119.0,"Action,Adventure,Comedy",7.0,242735,404500000,557600000,962100000,2017-12-20,90000000.0,9.644962e+08,8.744962e+08
Zootopia,108.0,"Adventure,Animation,Comedy",8.0,383446,341300000,682500000,1023800000,2016-03-04,150000000.0,1.019430e+09,8.694296e+08
Toy Story 3,103.0,"Adventure,Animation,Comedy",8.3,682218,415000000,652000000,1067000000,2010-06-18,200000000.0,1.068880e+09,8.688795e+08
Rogue One: A Star Wars Story,133.0,"Action,Adventure,Sci-Fi",7.8,478592,532200000,523900000,1056100000,2016-12-16,200000000.0,1.049103e+09,8.491029e+08
Bohemian Rhapsody,134.0,"Biography,Drama,Music",8.0,345466,216400000,687200000,903600000,2018-11-02,55000000.0,8.949853e+08,8.399853e+08
Finding Dory,97.0,"Adventure,Animation,Comedy",7.3,213542,486300000,542300000,1028600000,2016-06-17,200000000.0,1.021215e+09,8.212152e+08
The Secret Life of Pets,87.0,"Adventure,Animation,Comedy",6.5,161997,368400000,507100000,875500000,2016-07-08,75000000.0,8.867505e+08,8.117505e+08
The Dark Knight Rises,164.0,"Action,Thriller",8.4,1387769,448100000,636800000,1084900000,2012-07-20,275000000.0,1.084439e+09,8.094391e+08
Ice Age: Continental Drift,88.0,"Adventure,Animation,Comedy",6.6,175601,161300000,715900000,877200000,2012-07-13,95000000.0,8.797651e+08,7.847651e+08
The Hobbit: An Unexpected Journey,169.0,"Adventure,Family,Fantasy",7.9,719629,303000000,718100000,1021100000,2012-12-14,250000000.0,1.017004e+09,7.670036e+08
Deadpool,108.0,"Action,Adventure,Comedy",8.0,820847,363100000,420000000,783100000,2016-02-12,58000000.0,8.010256e+08,7.430256e+08
The Hunger Games: Catching Fire,146.0,"Action,Adventure,Sci-Fi",7.5,575455,424700000,440300000,865000000,2013-11-22,130000000.0,8.648680e+08,7.348680e+08
The Hobbit: The Desolation of Smaug,161.0,"Adventure,Fantasy",7.8,565563,258399999,700000000,958399999,2013-12-13,250000000.0,9.603669e+08,7.103669e+08
Spider-Man: Homecoming,133.0,"Action,Adventure,Sci-Fi",7.5,426302,334200000,546000000,880200000,2017-07-07,175000000.0,8.801664e+08,7.051664e+08
The Hobbit: The Battle of the Five Armies,144.0,"Adventure,Fantasy",7.4,438621,255100000,700900000,956000000,2014-12-17,250000000.0,9.455776e+08,6.955776e+08
Inside Out,95.0,"Adventure,Animation,Comedy",8.2,536181,356500000,501100000,857600000,2015-06-19,175000000.0,8.542360e+08,6.792360e+08
Deadpool 2,119.0,"Action,Adventure,Comedy",7.8,391735,318500000,460500000,779000000,2018-05-18,110000000.0,7.866806e+08,6.766806e+08
Inception,148.0,"Action,Adventure,Sci-Fi",8.8,1841066,292600000,535700000,828300000,2010-07-16,160000000.0,8.355246e+08,6.755246e+08
Wonder Woman,141.0,"Action,Adventure,Fantasy",7.5,487527,412600000,409300000,821900000,2017-06-02,150000000.0,8.211334e+08,6.711334e+08
Thor: Ragnarok,130.0,"Action,Adventure,Comedy",7.9,482995,315100000,538900000,854000000,2017-11-03,180000000.0,8.469800e+08,6.669800e+08
It,135.0,"Horror,Thriller",7.4,359123,327500000,372900000,700400000,2017-09-08,35000000.0,6.974580e+08,6.624580e+08
The Hunger Games: Mockingjay - Part 1,123.0,"Action,Adventure,Sci-Fi",6.6,379050,337100000,418200000,755300000,2014-11-21,125000000.0,7.665751e+08,6.415751e+08
The Twilight Saga: Eclipse,124.0,"Adventure,Drama,Fantasy",5.0,211733,300500000,398000000,698500000,2010-06-30,68000000.0,7.061028e+08,6.381028e+08
Pirates of the Caribbean: On Stranger Tides,136.0,"Action,Adventure,Fantasy",6.6,447624,241100000,804600000,1045700000,2011-05-20,410600000.0,1.045664e+09,6.350639e+08
Coco,105.0,"Adventure,Animation,Comedy",8.4,277194,209700000,597400000,807100000,2017-11-22,175000000.0,7.980081e+08,6.230081e+08
Batman v Superman: Dawn of Justice,151.0,"Action,Adventure,Fantasy",6.5,576909,330400000,543300000,873700000,2016-03-25,250000000.0,8.675003e+08,6.175003e+08
Madagascar 3: Europe's Most Wanted,93.0,"Adventure,Animation,Comedy",6.8,146858,216400000,530500000,746900000,2012-06-08,145000000.0,7.469213e+08,6.019213e+08
Guardians of the Galaxy,121.0,"Action,Adventure,Comedy",8.1,948394,333200000,440200000,773400000,2014-08-01,170000000.0,7.708675e+08,6.008675e+08
The Hunger Games,142.0,"Action,Adventure,Sci-Fi",7.2,795227,408000000,286400000,694400000,2012-03-23,80000000.0,6.779234e+08,5.979234e+08
Shrek Forever After,93.0,"Adventure,Animation,Comedy",6.3,167532,238700000,513900000,752600000,2010-05-21,165000000.0,7.562447e+08,5.912447e+08
Gravity,91.0,"Drama,Sci-Fi,Thriller",7.7,710018,274100000,449100000,723200000,2013-10-04,110000000.0,6.936987e+08,5.836987e+08
Spectre,148.0,"Action,Adventure,Thriller",6.8,352504,200100000,680600000,880700000,2015-11-06,300000000.0,8.796209e+08,5.796209e+08
Maleficent,97.0,"Action,Adventure,Family",7.0,305832,241400000,517100000,758500000,2014-05-30,180000000.0,7.585367e+08,5.785367e+08
Suicide Squad,123.0,"Action,Adventure,Fantasy",6.0,533039,325100000,421700000,746800000,2016-08-05,175000000.0,7.460599e+08,5.710599e+08
Sing,108.0,"Animation,Comedy,Family",7.1,115951,270400000,363800000,634200000,2016-12-21,75000000.0,6.344548e+08,5.594548e+08
Pirates of the Caribbean: Dead Men Tell No Tales,129.0,"Action,Adventure,Fantasy",6.6,228592,172600000,622300000,794900000,2017-05-26,230000000.0,7.882411e+08,5.582411e+08
X-Men: Days of Future Past,132.0,"Action,Adventure,Sci-Fi",8.0,620079,233900000,513900000,747800000,2014-05-23,200000000.0,7.478628e+08,5.478628e+08
The Martian,144.0,"Adventure,Drama,Sci-Fi",8.0,680116,228400000,401700000,630100000,2015-10-02,108000000.0,6.552714e+08,5.472714e+08
Captain America: The Winter Soldier,136.0,"Action,Adventure,Sci-Fi",7.8,666252,259800000,454500000,714300000,2014-04-04,170000000.0,7.144019e+08,5.444019e+08
Monsters University,104.0,"Adventure,Animation,Comedy",7.3,291887,268500000,475700000,744200000,2013-06-21,200000000.0,7.435883e+08,5.435883e+08
Dawn of the Planet of the Apes,130.0,"Action,Adventure,Drama",7.6,390199,208500000,502100000,710600000,2014-07-11,170000000.0,7.106446e+08,5.406446e+08
The Amazing Spider-Man,136.0,"Action,Adventure,Sci-Fi",7.0,525632,262000000,495900000,757900000,2012-07-03,220000000.0,7.578903e+08,5.378903e+08

In [79]:
##### RELEASE DATES / WORLDWIDEGROSS

In [80]:
triple_df['genres'].value_counts().head(20)

Action,Adventure,Sci-Fi       43
Adventure,Animation,Comedy    30
Action,Adventure,Fantasy      26
Comedy                        22
Comedy,Drama,Romance          19
Action,Adventure,Drama        19
Comedy,Romance                17
Drama,Romance                 17
Action,Crime,Drama            16
Action,Adventure,Comedy       15
Action,Comedy,Crime           15
Action,Crime,Thriller         13
Comedy,Drama                  13
Action,Thriller               13
Action,Adventure,Animation    12
Drama                         12
Biography,Drama,History       11
Horror,Mystery,Thriller       10
Crime,Drama,Thriller          10
Action,Adventure,Thriller     10
Name: genres, dtype: int64

In [81]:
triple_df.columns

Index(['runtime_minutes', 'genres', 'averagerating', 'numvotes',
       'domestic_gross', 'foreign_gross', 'total_gross', 'release_date',
       'production_budget', 'worldwide_gross', 'roi'],
      dtype='object')

In [82]:
# Rename all the columns to capitalize
#triple_df.columns = [col.capitalize() for col in triple_df.columns]

In [83]:
triple_df.head(60)

,runtime_minutes,genres,averagerating,numvotes,domestic_gross,foreign_gross,total_gross,release_date,production_budget,worldwide_gross,roi
10 Cloverfield Lane,103.0,"Drama,Horror,Mystery",7.2,260383,72100000,38100000,110200000,2016-03-11,5000000.0,1.082864e+08,1.032864e+08
12 Years a Slave,134.0,"Biography,Drama,History",8.1,577301,56700000,131100000,187800000,2013-10-18,20000000.0,1.810253e+08,1.610253e+08
127 Hours,94.0,"Adventure,Biography,Drama",7.6,323949,18300000,42400000,60700000,2010-11-05,18000000.0,6.021717e+07,4.221717e+07
2 Guns,109.0,"Action,Comedy,Crime",6.7,182025,75600000,56300000,131900000,2013-08-02,61000000.0,1.324930e+08,7.149302e+07
21 Jump Street,109.0,"Action,Comedy,Crime",7.2,477771,138400000,63100000,201500000,2012-03-16,42000000.0,2.028124e+08,1.608124e+08
22 Jump Street,112.0,"Action,Comedy,Crime",7.0,319504,191700000,139600000,331300000,2014-06-13,50000000.0,3.313339e+08,2.813339e+08
3 Days to Kill,117.0,"Action,Drama,Thriller",6.2,81681,30700000,21900000,52600000,2014-02-21,28000000.0,3.895990e+07,1.095990e+07
30 Minutes or Less,83.0,"Action,Comedy,Crime",6.1,87254,37100000,3500000,40600000,2011-08-12,28000000.0,4.096672e+07,1.296672e+07
47 Ronin,128.0,"Action,Adventure,Drama",6.3,135754,38400000,113400000,151800000,2013-12-25,175000000.0,1.517168e+08,-2.328318e+07
50/50,100.0,"Comedy,Drama,Romance",7.7,300475,35000000,4200000,39200000,2011-09-30,8000000.0,4.133474e+07,3.333474e+07
A Dangerous Method,99.0,"Biography,Drama,Romance",6.4,93259,5700000,21800000,27500000,2011-11-23,20000000.0,1.480753e+07,-5.192469e+06
A Good Day to Die Hard,98.0,"Action,Thriller",5.3,188383,67300000,237300000,304600000,2013-02-14,92000000.0,3.042492e+08,2.122492e+08
A Monster Calls,108.0,"Animation,Drama,Fantasy",7.5,70416,3700000,43600000,47300000,2017-01-06,43000000.0,4.641453e+07,3.414530e+06
A Most Wanted Man,122.0,"Crime,Drama,Thriller",6.8,67914,17200000,19000000,36200000,2014-07-25,15000000.0,3.606889e+07,2.106889e+07
A Quiet Place,90.0,"Drama,Horror,Sci-Fi",7.6,305031,188000000,152900000,340900000,2018-04-06,17000000.0,3.345223e+08,3.175223e+08
A Simple Favor,117.0,"Comedy,Crime,Drama",6.9,83338,53500000,44100000,97600000,2018-09-14,20000000.0,9.762872e+07,7.762872e+07
A Walk Among the Tombstones,114.0,"Action,Crime,Drama",6.5,105116,26300000,26900000,53200000,2014-09-19,28000000.0,6.210859e+07,3.410859e+07
Abduction,106.0,"Action,Mystery,Thriller",5.1,72552,28100000,54000000,82100000,2011-09-23,35000000.0,8.664836e+07,5.164836e+07
About Time,123.0,"Comedy,Drama,Fantasy",7.8,263136,15300000,71800000,87100000,2013-11-01,12000000.0,8.930918e+07,7.730918e+07
Abraham Lincoln: Vampire Hunter,105.0,"Action,Fantasy,Horror",5.9,142853,37500000,79000000,116500000,2012-06-22,67500000.0,1.374897e+08,6.998973e+07
After Earth,100.0,"Action,Adventure,Drama",4.8,181687,60500000,183300000,243800000,2013-05-31,130000000.0,2.514997e+08,1.214997e+08
Alice Through the Looking Glass,113.0,"Adventure,Family,Fantasy",6.2,79951,77000000,222400000,299400000,2016-05-27,170000000.0,2.769281e+08,1.069281e+08
Alien: Covenant,122.0,"Horror,Sci-Fi,Thriller",6.4,226920,74300000,166600000,240900000,2017-05-19,97000000.0,2.385212e+08,1.415212e+08
Allied,124.0,"Action,Drama,Romance",7.1,125741,40100000,79400000,119500000,2016-11-23,106000000.0,1.192667e+08,1.326666e+07
American Hustle,138.0,"Crime,Drama",7.2,418221,150100000,101100000,251200000,2013-12-13,40000000.0,2.578783e+08,2.178783e+08
American Made,115.0,"Action,Biography,Comedy",7.2,131043,51300000,83500000,134800000,2017-09-29,50000000.0,1.355692e+08,8.556921e+07
American Reunion,113.0,Comedy,6.7,192250,57000000,178000000,235000000,2012-04-06,50000000.0,2.367992e+08,1.867992e+08
American Sniper,133.0,"Action,Biography,Drama",7.3,401915,350100000,197300000,547400000,2014-12-25,58000000.0,5.473264e+08,4.893264e+08
American Ultra,96.0,"Action,Comedy,Sci-Fi",6.1,76769,14400000,12700000,27100000,2015-08-21,28000000.0,3.029503e+07,2.295028e+06
Amour,127.0,"Drama,Romance",7.9,84960,6700000,13100000,19800000,2012-12-19,9700000.0,3.678704e+07,2.708704e+07
Anchorman 2: The Legend Continues,119.0,Comedy,6.3,156116,125200000,46300000,171500000,2013-12-18,50000000.0,1.721858e+08,1.221858e+08
Anna Karenina,129.0,"Drama,Romance",6.6,84668,12800000,56100000,68900000,2012-11-16,49000000.0,7.100463e+07,2.200463e+07
Annabelle,99.0,"Horror,Mystery,Thriller",5.4,122039,84300000,172800000,257100000,2014-10-03,6500000.0,2.568629e+08,2.503629e+08
Annabelle: Creation,109.0,"Horror,Mystery,Thriller",6.5,90402,102100000,204400000,306500000,2017-08-11,15000000.0,3.053849e+08,2.903849e+08
Another Earth,92.0,"Drama,Romance,Sci-Fi",7.0,85839,1300000,456000,1756000,2011-07-22,175000.0,2.102779e+06,1.927779e+06
Ant-Man,117.0,"Action,Adventure,Comedy",7.3,501213,180200000,339100000,519300000,2015-07-17,130000000.0,5.188584e+08,3.888584e+08
Ant-Man and the Wasp,118.0,"Action,Adventure,Comedy",7.1,244024,216600000,406000000,622600000,2018-07-06,130000000.0,6.231447e+08,4.931447e+08
Aquaman,143.0,"Action,Adventure,Fantasy",7.1,263328,335100000,812700000,1147800000,2018-12-21,160000000.0,1.146895e+09,9.868946e+08
Argo,120.0,"Biography,Drama,Thriller",7.7,534683,136000000,96300000,232300000,2012-10-12,44500000.0,2.271408e+08,1.826408e+08
Arrival,116.0,"Drama,Mystery,Sci-Fi",7.9,515483,100500000,102800000,203300000,2016-11-11,47000000.0,2.031279e+08,1.561279e+08
Atomic Blonde,115.0,"Action,Mystery,Thriller",6.7,150407,51700000,48300000,100000000,2017-07-28,30000000.0,9.834542e+07,6.834542e+07
Attack the Block,88.0,"Action,Comedy,Sci-Fi",6.7,93868,1000000,4800000,5800000,2011-07-29,13000000.0,6.459183e+06,-6.540817e+06
August: Osage County,121.0,"Comedy,Drama",7.2,79383,37700000,36500000,74200000,2013-12-25,25000000.0,5.073881e+07,2.573881e+07
Avengers: Age of Ultron,141.0,"Action,Adventure,Sci-Fi",7.3,665594,459000000,946400000,1405400000,2015-05-01,330600000.0,1.403014e+09,1.072414e+09
Avengers: Infinity War,149.0,"Action,Adventure,Sci-Fi",8.5,670926,678800000,1369000000,2047800000,2018-04-27,300000000.0,2.048134e+09,1.748134e+09
Baahubali 2: The Conclusion,167.0,"Action,Drama",8.3,65656,20200000,234000000,254200000,2017-04-28,30000000.0,2.635029e+08,2.335029e+08
Baby Driver,113.0,"Action,Crime,Drama",7.6,363977,107800000,119100000,226900000,2017-06-28,34000000.0,2.281042e+08,1.941042e+08
Bad Moms,100.0,Comedy,6.2,100952,113300000,70700000,184000000,2016-07-29,20000000.0,1.809987e+08,1.609987e+08
Bad Teacher,92.0,"Comedy,Romance",5.7,181189,100300000,115900000,216200000,2011-06-24,19000000.0,2.154490e+08,1.964490e+08
Batman v Superman: Dawn of Justice,151.0,"Action,Adventure,Fantasy",6.5,576909,330400000,543300000,873700000,2016-03-25,250000000.0,8.675003e+08,6.175003e+08
Battleship,131.0,"Action,Adventure,Sci-Fi",5.8,225342,65400000,237600000,303000000,2012-05-18,220000000.0,3.134777e+08,9.347772e+07
Baywatch,116.0,"Action,Comedy,Crime",5.6,137528,58100000,119800000,177900000,2017-05-25,60000000.0,1.758638e+08,1.158638e+08
Beastly,86.0,"Drama,Fantasy,Romance",5.6,72599,27900000,15300000,43200000,2011-03-04,17000000.0,3.802823e+07,2.102823e+07
Beasts of the Southern Wild,93.0,"Adventure,Drama,Fantasy",7.3,77440,12800000,8300000,21100000,2012-06-27,1800000.0,2.326513e+07,2.146513e+07
Before Midnight,109.0,"Drama,Romance",7.9,123107,8100000,3100000,11200000,2013-05-24,3000000.0,2.325193e+07,2.025193e+07
Begin Again,104.0,"Comedy,Drama,Music",7.4,129884,16200000,47300000,63500000,2014-06-27,8000000.0,6.883874e+07,6.083874e+07
Beginners,105.0,"Comedy,Drama,Romance",7.2,83770,5800000,8500000,14300000,2011-06-03,3200000.0,1.431441e+07,1.111441e+07
Big Eyes,106.0,"Biography,Crime,Drama",7.0,77447,14500000,14800000,29300000,2014-12-25,10000000.0,2.731787e+07,1.731787e+07
Big Hero 6,102.0,"Action,Adventure,Animation",7.8,371204,222500000,435300000,657800000,2014-11-07,165000000.0,6.521278e+08,4.871278e+08
Biutiful,148.0,"Drama,Romance",7.5,80382,5100000,20000000,25100000,2011-01-28,35000000.0,2.468752e+07,-1.031248e+07

In [84]:
def contains_action(text):
    if 'Action' in text:
        return True
    else:
        return False

In [85]:
triple_df['genres'].map(contains_action).sum()

270

In [86]:
def contains_adventure(text):
    if 'Adventure' in text:
        return True
    else:
        return False

In [87]:
triple_df['genres'].map(contains_adventure).sum()

215

In [88]:
def contains_scifi(text):
    if 'Sci-Fi' in text:
        return True
    else:
        return False

In [89]:
triple_df['genres'].map(contains_scifi).sum()

90

In [90]:
def contains_action(text):
    if 'Action' in text:
        return True
    else:
        return False

In [91]:
triple_df

,runtime_minutes,genres,averagerating,numvotes,domestic_gross,foreign_gross,total_gross,release_date,production_budget,worldwide_gross,roi
10 Cloverfield Lane,103.0,"Drama,Horror,Mystery",7.2,260383,72100000,38100000,110200000,2016-03-11,5000000.0,1.082864e+08,103286422.0
12 Years a Slave,134.0,"Biography,Drama,History",8.1,577301,56700000,131100000,187800000,2013-10-18,20000000.0,1.810253e+08,161025343.0
127 Hours,94.0,"Adventure,Biography,Drama",7.6,323949,18300000,42400000,60700000,2010-11-05,18000000.0,6.021717e+07,42217171.0
2 Guns,109.0,"Action,Comedy,Crime",6.7,182025,75600000,56300000,131900000,2013-08-02,61000000.0,1.324930e+08,71493015.0
21 Jump Street,109.0,"Action,Comedy,Crime",7.2,477771,138400000,63100000,201500000,2012-03-16,42000000.0,2.028124e+08,160812429.0
...,...,...,...,...,...,...,...,...,...,...,...
X-Men: First Class,131.0,"Action,Adventure,Sci-Fi",7.7,608930,146400000,207200000,353600000,2011-06-03,160000000.0,3.554083e+08,195408305.0
Young Adult,94.0,"Comedy,Drama",6.3,74071,16300000,6600000,22900000,2011-12-09,12000000.0,2.275036e+07,10750356.0
Your Highness,102.0,"Adventure,Comedy,Fantasy",5.5,92940,21600000,3300000,24900000,2011-04-08,50000000.0,2.612164e+07,-23878362.0
Zero Dark Thirty,157.0,"Drama,Thriller",7.4,251072,95700000,37100000,132800000,2012-12-19,52500000.0,1.346124e+08,82112435.0
Zootopia,108.0,"Adventure,Animation,Comedy",8.0,383446,341300000,682500000,1023800000,2016-03-04,150000000.0,1.019430e+09,869429616.0

In [92]:
#################### VISUAL EXAMPLES################################
#import matplotlib.pyplot as plt

# Set up figure and axes
#fig, (ax1, ax2) = plt.subplots(ncols=2, figsize=(12, 7))
#fig.set_tight_layout(True)

# Histogram of Wins and Frequencies
#ax1.hist(x=wins, bins=range(8), align="left", color="green")
#ax1.set_xticks(range(7))
#ax1.set_xlabel("Wins in 2018 World Cup")
#ax1.set_ylabel("Frequency")
#ax1.set_title("Distribution of Wins")

## Horizontal Bar Graph of Wins by Country
#ax2.barh(teams[::-1], wins[::-1], color="green")
#ax2.set_xlabel("Wins in 2018 World Cup")
#ax2.set_title("Wins by Country");

##################################################################
# Set up figure
#fig, ax = plt.subplots(figsize=(8, 5))

# Basic scatter plot
#ax.scatter(
#    x=populations,
#    y=wins,
#    color="gray", alpha=0.5, s=100
#)
#ax.set_xlabel("2018 Population")
#ax.set_ylabel("2018 World Cup Wins")
#ax.set_title("Population vs. World Cup Wins")

# Add annotations for specific points of interest
#highlighted_points = {
#    "Belgium": 2, # Numbers are the index of that
#    "Brazil": 3,  # country in populations & wins
#    "France": 10,
#    "Nigeria": 17
#}
#for country, index in highlighted_points.items():
    # Get x and y position of data point
#    x = populations[index]
#    y = wins[index]
    # Move each point slightly down and to the left
    # (numbers were chosen by manually tweaking)
#    xtext = x - (1.25e6 * len(country))
#    ytext = y - 0.5
    # Annotate with relevant arguments
#    ax.annotate(
#        text=country,
#        xy=(x, y),
#        xytext=(xtext, ytext)
#    )

## Data Modeling
Describe and justify the process for analyzing or modeling the data.

Questions to consider:

* How did you analyze or model the data?
* How did you iterate on your initial approach to make it better?
* Why are these choices appropriate given the data and the business problem?

In [93]:
###usa_2016_gold_medals = []

##for row in olympics_data:
##    if row["Medal"] == "G" and row["Nationality"] == "USA" and row["Year"] == "2016":
##        usa_2016_gold_medals.append({"Event": row["Event"], "Name": row["Name"]})
        
## usa_2016_gold_medals

## Evaluation

Evaluate how well your work solves the stated business problem.

Questions to consider:

* How do you interpret the results?
* How well does your model fit your data? How much better is this than your baseline model?
* How confident are you that your results would generalize beyond the data you have?
* How confident are you that this model would benefit the business if put into use?

## Conclusions

Provide your conclusions about the work you've done, including any limitations or next steps.


Questions to consider:

* What would you recommend the business do as a result of this work?
* What are some reasons why your analysis might not fully solve the business problem?
* What else could you do in the future to improve this project?